### ISSUE TITLE
Sidebar shows always toggle button

### ISSUE THREAD

**Issue by rranzmaier** [vikramlearning/blazorbootstrap#144]
I copied the sample code from the demo "Full layout with sidebar" and my sidebar shows always a Toggle Button.
I haven't found a property to disable this functionality and no property or method to set the sidebar to expanded on startup.

I'm using the latest Version 1.4.1 
.net 7.0
Bootstrap 5.1.3
Issue occur in Webassembly and ServiceSide version

If this is a new feature. Please add a Method or Property to set it the menu is expanded or not. The Toggle Function is nice but not useful in this case. 

VS 2022 Default Empty Blazor Template
Added Code from Getstarted
Replaced MainLayout.cs with this code

```
@inherits LayoutComponentBase
<div class="bb-page">

    <Sidebar @ref="sidebar"
             IconName="IconName.BootstrapFill"
             Title="Blazor Bootstrap"
             DataProvider="SidebarDataProvider" />

    <main>
        <div class="bb-top-row px-4 d-flex justify-content-end">
            <a href="https://docs.microsoft.com/aspnet/" target="_blank">About</a>
        </div>

        <article class="content px-4">
            <div class="py-2">Page content goes here</div>
        </article>
    </main>

</div>
@code {
    Sidebar sidebar;
    IEnumerable<NavItem> navItems;

    private async Task<SidebarDataProviderResult> SidebarDataProvider(SidebarDataProviderRequest request)
    {
        if (navItems is null)
            navItems = GetNavItems();

        return await Task.FromResult(request.ApplyTo(navItems));
    }

    private IEnumerable<NavItem> GetNavItems()
    {
        navItems = new List<NavItem>
        {
            new NavItem { Id = "1", Href = "/getting-started", IconName = IconName.HouseDoorFill, Text = "Getting Started"},

            new NavItem { Id = "2", IconName = IconName.LayoutSidebarInset, Text = "Content", IconColor = IconColor.Primary },
            new NavItem { Id = "3", Href = "/icons", IconName = IconName.PersonSquare, Text = "Icons", ParentId="2"},

            new NavItem { Id = "4", IconName = IconName.ExclamationTriangleFill, Text = "Components", IconColor = IconColor.Success },
            new NavItem { Id = "5", Href = "/alerts", IconName = IconName.CheckCircleFill, Text = "Alerts", ParentId="4"},
            new NavItem { Id = "6", Href = "/breadcrumb", IconName = IconName.SegmentedNav, Text = "Breadcrumb", ParentId="4"},
            new NavItem { Id = "7", Href = "/sidebar", IconName = IconName.LayoutSidebarInset, Text = "Sidebar", ParentId="4"},

            new NavItem { Id = "8", IconName = IconName.WindowPlus, Text = "Forms", IconColor = IconColor.Danger },
            new NavItem { Id = "9", Href = "/autocomplete", IconName = IconName.InputCursorText, Text = "Auto Complete", ParentId="8"},
            new NavItem { Id = "10", Href = "/currency-input", IconName = IconName.CurrencyDollar, Text = "Currency Input", ParentId="8"},
            new NavItem { Id = "11", Href = "/number-input", IconName = IconName.InputCursor, Text = "Number Input", ParentId="8"},
            new NavItem { Id = "12", Href = "/switch", IconName = IconName.ToggleOn, Text = "Switch", ParentId="8"},
        };

        return navItems;
    }
}
```

![image](https://user-images.githubusercontent.com/7863837/214175361-8b335445-85f2-4667-b11f-ef84c67b704c.png)
After clicking the toggle button:
![image](https://user-images.githubusercontent.com/7863837/214175424-f1a42daf-b710-4a64-8011-17893be9a322.png)

**Comment by gvreddy04** [comment]
@rranzmaier Thank you for reaching us.

I don't know if the CSS isolation has any bug in the .NET 7 Empty Templates version or any other reason. The Sidebar specific CSS was not loaded. Added CSS isolation related file reference in the index.html file, then which worked.

I'll investigate the issue and update you.

![image](https://user-images.githubusercontent.com/2337067/214290217-6f615697-f932-4c20-ba59-aa7e886683d4.png)

**NOTE:** 
The toggle icon showing there should be visible only on the mobile view. We have a separate example to toggle the sidebar to show the icons only.

Link: https://demos.blazorbootstrap.com/sidebar#toggle-sidebar-to-show-icons-only

**Comment by gvreddy04** [comment]
@rranzmaier This is a known bug in the **Empty Blazor project templates**. 

Refer: [Blazor empty template doesn't load scoped CSS #43975](https://github.com/dotnet/aspnetcore/issues/43975)

**Comment by gvreddy04** [comment]
**Solution:** 

Add the below link in the `index.html` file `head` section, as shown in the screenshot.
```html
<link href="_content/Blazor.Bootstrap/Blazor.Bootstrap.bundle.scp.css" rel="stylesheet" />
```
**Screenshot:**

![image](https://user-images.githubusercontent.com/2337067/214626357-b901f9bb-0890-4459-a09b-af111fc3b004.png)
