### ISSUE TITLE
AutoComplete throws exception "Error: Microsoft.JSInterop.JSException: Failed to execute 'querySelector' on 'Document': '0HMN98T70T4ID'

### ISSUE THREAD

**Issue by vikneshkumar** [vikramlearning/blazorbootstrap#146]
When I added autocomplete inside the Devexpress grid, I encountered the identical problem(https://github.com/vikramlearning/blazorbootstrap/issues/97#issue-1376432426). As stated in the comments, it works perfectly when I go back to version 0.4.0. I'm currently using version 1.3.1.

https://supportcenter.devexpress.com/ticket/details/t1136877/dxgrid-custom-control-in-dxformlayoutitem-microsoft-jsinterop-jsexception-failed-to

**Comment by gvreddy04** [comment]
@vikneshkumar Can you attach minimal repro project here?

**Comment by vikneshkumar** [comment]
In the DxFormLayoutItem for the EditFormTemplate, I've inserted the autocomplete control. After clicking the Save or Cancel button, I received the message "Error: Microsoft.JSInterop.JSException: Failed to execute 'querySelector' on 'Document': '0HMN98T70T4ID' is not a valid selector." Autocomplete works fine when i search some inputs and assigned to EditFormContext.

[AutoComplete.zip](https://github.com/vikramlearning/blazorbootstrap/files/10518342/AutoComplete.zip)

**Comment by vikneshkumar** [comment]
@gvreddy04  Thank you, problem is resolved.
