### ISSUE TITLE
Please add identity support to your templates

### ISSUE THREAD

**Issue by Duelbat** [vikramlearning/blazorbootstrap#164]
This is a beautiful component suite! If your template includes and option for Microsoft identity, I would use it exclusively and would sign up for support.

Many thanks
Luke

**Comment by gvreddy04** [comment]
@Duelbat Are you looking for WebAssembly template or Server Template?

**Comment by gvreddy04** [comment]
@Duelbat This will be resolved part of #165

**Comment by gvreddy04** [comment]
@Duelbat Please check the repo: https://github.com/vikramlearning/blazorbootstrap-project-templates

Screenshot:
![image](https://github.com/vikramlearning/blazorbootstrap/assets/2337067/33d9caf4-f0d9-444c-b686-8ae2d75c364c)
