### ISSUE TITLE
Create templates for dotnet new util

### ISSUE THREAD

**Issue by szyb** [vikramlearning/blazorbootstrap#165]
It would be very useful, if all those template projects would be accessible by using `dotnet new` util (https://learn.microsoft.com/en-us/dotnet/core/tools/custom-templates). Would it be possible?

**Comment by gvreddy04** [comment]
@szyb FYI

Install with .NET CLI: `dotnet new install Blazor.Bootstrap.Templates::1.8.0`

![image](https://github.com/vikramlearning/blazorbootstrap/assets/2337067/4ce5c8ba-3fef-4e1d-8110-f7142619f173)
