### ISSUE TITLE
Autocomplete component: Disabled property not updating

### ISSUE THREAD

**Issue by giarico** [vikramlearning/blazorbootstrap#167]
Hello,
When i assign a variable (or a condition) to the "Disabled" property, if the value changes the Disabled property doesn't change accordingly.

Example:
<input type="checkbox" @bind="disabled" />
<AutoComplete @bind-Value="productDisplayName"
			  TItem="ProductDTO"
			  DataProvider="ProductDataProvider"
			  PropertyName="DisplayName"
			  Placeholder="Type to search..."
			  OnChanged="(ProductDTO item) => OnProductChanged(item)"
			  Disabled="@disabled" />

**Comment by gvreddy04** [comment]
@giarico You can now follow CurrencyInput, TimeInput, and other examples where we documented how to disable the control.

`Currency Input`: https://demos.blazorbootstrap.com/form/currency-input#disable
`Time Input`: https://demos.blazorbootstrap.com/form/time-input#disable

![image](https://user-images.githubusercontent.com/2337067/227506462-773b060d-1361-4733-b636-9b8c1f53350c.png)

In the next release, we will update the documentation for this component. And will make the disable feature more consistent for all the form components. Also, we support both the method and property.

**Comment by giarico** [comment]
Thank you for the help!
