### ISSUE TITLE
Chart options to control the chart's animation

### ISSUE THREAD

**Issue by stinus** [vikramlearning/blazorbootstrap#171]
This is a feature request to allow control over the animation of the charts. Chart.js has an animation built in which animates the chart every time it updates. As I was working with real-time data and getting second by second updates, the chart in blazorbootstrap updates with an ease-in animation from bottom to top every few seconds. 
![LineChart](https://user-images.githubusercontent.com/16155547/228632970-7dbc4626-57bd-46e5-84a9-9a1dccaff316.gif)

It would be nice if we can control the animation the same way chart.js allows it like this:
![Chart js](https://user-images.githubusercontent.com/16155547/228633754-64631e24-7169-43e0-acb0-733e4c56dd4b.gif)

For example https://www.chartjs.org/docs/latest/samples/line/line.html if you click 'add data' the only update happening is adding the datapoint to the end of the chart and scaling it correctly without that ease-in effect that the linechart in blazorbootstrap seems to have by default.

**Comment by LukasHKlg** [comment]
Any updates on this issue?

**Comment by gvreddy04** [comment]
@stinus We will include in **1.10.0**.

**Comment by gvreddy04** [comment]
@stinus @LukasHKlg 

You can check the WIP demos here: 
- Blazor Line Chart: https://gray-wave-0e4848710-302.centralus.azurestaticapps.net/charts/line-chart
- Blazor Bar Chart: https://gray-wave-0e4848710-302.centralus.azurestaticapps.net/charts/bar-chart
-

**Comment by LukasHKlg** [comment]
> @stinus @LukasHKlg
> 
> You can check the WIP demos here:
> 
> * Blazor Line Chart: https://gray-wave-0e4848710-302.centralus.azurestaticapps.net/charts/line-chart
> * Blazor Bar Chart: https://gray-wave-0e4848710-302.centralus.azurestaticapps.net/charts/bar-chart
> * Blazor Doughnut Chart: In-progress
> * Blazor Pie Chart: In-progress
> 
> We are making the same enhancements to all chart components.

Got 404 on both links.

**Comment by gvreddy04** [comment]
@LukasHKlg The features have already been merged to the **master** branch. When changes are merged to the master branch, the **preview deployment slot** is deleted. However, I can share the preview here. **1.10.0** will be released on or before **August 12, 2023**.


https://github.com/vikramlearning/blazorbootstrap/assets/2337067/575b9136-e29c-4f10-98db-08023e7aadca
