### ISSUE TITLE
Grid Selection

### ISSUE THREAD

**Issue by thuyenvinh** [vikramlearning/blazorbootstrap#179]
Please add the feature of editing data on the grid similar to https://tabblazor.com/docs/tables.

**Comment by gvreddy04** [comment]
@thuyenvinh Until we ship this feature, you can try the below custom approach, where we created a sample GitHub repo.

[Grid - Edit / Delete / Single Selection / Multi Selection](https://github.com/vikramlearning/blazorbootstrap/discussions/176)

**Comment by gvreddy04** [comment]
Grid in-line editing is covered part of **Edit mode in grid component (in line editing ) #123**.

**Comment by gvreddy04** [comment]
Sample screenshot:

![image](https://github.com/vikramlearning/blazorbootstrap/assets/2337067/94725aa8-d46e-4b9b-849e-255d7dfde61b)
