### ISSUE TITLE
Show Autocomplete reset button when default value set

### ISSUE THREAD

**Issue by giarico** [vikramlearning/blazorbootstrap#183]
Hello,

The reset button on the autocomplete component doesn't appear when the value is set without selecting the item from the data provider.

Example: the SupplierDisplayName is retrived from the database.

<AutoComplete @bind-Value="SupplierDisplayName"
                                  TItem="SupplierDTO"
                                  DataProvider="SupplierDataProvider"
                                  PropertyName="DisplayName"
                                  Placeholder="Type to search..."
                                  OnChanged="(SupplierDTO item) => OnSupplierChanged(item)" />

**Comment by gvreddy04** [comment]
@giarico Thanks for using our components. We are uanble to reproduce this issue. Could you please provide more details or share a sample GitHub repo.

**Required Details:**
BlazorWeb Assembly / Server:
.NET 6 / .NET 7:
Browser:
Browser Version: 
Sample Code:
GitHub Repo:

**Comment by giarico** [comment]
Here you are...

```
@page "/"

<AutoComplete @bind-Value="SupplierDisplayName"
TItem="SupplierDTO"
DataProvider="SupplierDataProvider"
PropertyName="DisplayName"
Placeholder="Type to search..." />

@code {
    private string SupplierDisplayName = "";

    protected override void OnInitialized()
    {
        SupplierDisplayName = "S1 - Supplier 1";
    }

    private async Task<AutoCompleteDataProviderResult<SupplierDTO>> SupplierDataProvider(AutoCompleteDataProviderRequest<SupplierDTO> request)
    {
        var items = new List<SupplierDTO>
        {
            new SupplierDTO { Code = "S1", Description = "Supplier 1" },
            new SupplierDTO { Code = "S2", Description = "Supplier 2" }
        };
        return await Task.FromResult(new AutoCompleteDataProviderResult<SupplierDTO> { Data = items, TotalCount = items.Count() });
    }

    public class SupplierDTO
    {
        public string Code { get; set; } = default!;
        public string Description { get; set; } = default!;
        public string DisplayName { get => $"{Code} - {Description}"; }
    }
}
```
