### ISSUE TITLE
A CSS rule could be more targeted to not interfere with others

### ISSUE THREAD

**Issue by francis-chiss** [vikramlearning/blazorbootstrap#184]
I was using the Bootstrap dropdown inside a table, and after installing this library, its cosmetics changed (the arrow down dissapeared).

I quickly tracked it down to the following CSS rule in blazor.bootstrap.css  :

![image](https://user-images.githubusercontent.com/7947837/232145550-6b4c9351-84da-415b-9724-bd326391a23a.png)

Putting content: "" instead made it work, but that's obviously not the best fix.

I presume this rule is there so that other components using it (DatePicker? other?) are sized correctly, but as stated previously, it's also impacting non-related elements.

**Comment by gvreddy04** [comment]
@francis-chiss Thank you for using our components. Could you please share a sample code or GitHub repo to understand the scenario?

**Comment by francis-chiss** [comment]
Sure, just use the following in a Blazor page:

`<table>
    <thead><td>Like Bootstrap suggests</td><td>With workaround</td></thead>
    <tbody>
    <td>
        <button class="btn btn-primary btn-sm pb-0 dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false"></button>
    </td>
    <td>
        <button class="btn btn-primary btn-sm pb-0 dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
            <i class="bi-caret-down-fill" style="font-size: 0.6rem; vertical-align: middle"></i>
        </button>
    </td>
    </tbody>
</table>`
