### ISSUE TITLE
Switch component : disabled state cannot be set with variables

### ISSUE THREAD

**Issue by DutchJaFO** [vikramlearning/blazorbootstrap#185]
This does not work as expected as 'Disabled' parameter ignored.

`<Switch Label="Show details" Disabled="@MyDisabledState">
`

**Comment by gvreddy04** [comment]
@DutchJaFO Thank you for using our components. 

Please use **Enable()** or **Disable()** methods to change the disable behaviour of the Switch. In the feature will make all the form components consistent.

Switch: https://demos.blazorbootstrap.com/form/switch#disable

![image](https://user-images.githubusercontent.com/2337067/232246685-deb44822-5255-4682-bc74-5ca10b0f40c9.png)

Other References: 
- https://github.com/vikramlearning/blazorbootstrap/issues/167

**Comment by gvreddy04** [comment]
@DutchJaFO Will make this consistent in the next release.
