### ISSUE TITLE
.NET 7.0 loading progress support

### ISSUE THREAD

**Issue by kaniosm** [vikramlearning/blazorbootstrap#191]
The documentation suggests removing app.css when using the SideBar component which removes support for the loading-progress, hence the corresponding div should be removed from index.html as well.

Do you have any plans in the future to support the loading-progress or even better ensure compatibility with app.css?

**Comment by gvreddy04** [comment]
@kaniosm Thank you for trying our components. Yes, we are working on the templates. This is a work in progress. Please expect cleaner templates in a week or so. 

Find the new **Blazor Bootstrap Templates** repo [here](https://github.com/vikramlearning/blazorbootstrap-project-templates).

**Comment by kaniosm** [comment]
Many thanks for the update @gvreddy04 !

**Comment by gvreddy04** [comment]
This will be resolved part of #165.
