### ISSUE TITLE
Grid calls DataProvider method after input's onchange event v1.7.2

### ISSUE THREAD

**Issue by ervintuzlic** [vikramlearning/blazorbootstrap#195]
I'm testing the v1.7.2 version. I already have a lot of pages where I have used Grid component on v1.3.0. In each grid I have a column with an input type checkbox with onchange event that calls method e.g AddSomethingToSelection.
However, after going through method 'AddSomethingToSelection' the DataProvider method will be called again and go to server and get data. This wasn't the case on v1.3.0. 

Is there a way to disable this behavior as I don't want DataProvider to be called each time some action is performed on grid. This causes grid to flicker for a second each time checkbox is clicked.

**Comment by gvreddy04** [comment]
@ervintuzlic Can you share a sample GitHub repo to understand the issue and you Grid design?

**Comment by ervintuzlic** [comment]
I have sent invitation. I've done test in Counter.razor page. I used button in this example for simplicity reasons. The outcome is the same after method ChangeTemperature is finished it calls again ForecastDataProvider this is not the case in v1.3.0.

**Comment by gvreddy04** [comment]
Link: https://github.com/ervintuzlic/GridTestDataProvider

**Comment by gvreddy04** [comment]
@ervintuzlic Thank you for the sample code. I'm able to replicate the behavior. I have a question, Why you are updating the grid information on the client side? What do you want to achieve here? Please give as much as details to understand you entire workflow here.

Because we want to give a permanent solution keeping in mind other users.

**Comment by ervintuzlic** [comment]
I apologize for the confusion I will try to give more context about this issue. 

So in my main project due to number of records I have in database I need to use **server side filtering, paging and sorting**. That's why I used in my new repo that I shared with you following code in line 35:

`return await Task.FromResult(new GridDataProviderResult<WeatherForecast> { Data = Forecasts!, TotalCount = Forecasts!.Count });`

Instead the one that is mentioned in client side filtering (Sorry for not explaining this well before your investigation).

Considering this I can't really have some condition like you wrote in **line 54** in this example, as TotalCount is required for server side filtering:
[Grid - Edit / Delete / Single Selection / Multi Selection](https://github.com/vikramlearning/blazorbootstrap-examples/blob/master/src/BlazorBootstrap.Examples/BlazorBootstrap.Examples/Pages/Employee/Employees.razor)

With all this mentioned I will try to explain the issue a bit better. When I use server side filtering the GridProvider method is called when event on button, checkbox or some input is registered. This comes as inconvenience as if you would have checkbox in each row that marks something checked/unchecked every time you press that checkbox it would go to server to get data.

**Comment by gvreddy04** [comment]
@ervintuzlic We are currently working on adding a row selection feature (select/ select all) as part of **Grid Select and Edit Inline** #179. This feature will eliminate the need for custom logic. Please note that this is still a work in progress. We are planning to release this feature as part of version 1.8.0. If you have any questions, please let us know.

**Comment by ervintuzlic** [comment]
Yes that feature would resolve the select part, but that's not the issue I am referring to. 

For example what if I had server side filtering and button in each row that onclick event calls method OpenEditModal. 
This would cause every time I click on the button that opens Edit Modal for that record grid to flicker behind because it goes to the server for data and returns.

I hope this example gives you more context about issue.

**Comment by gvreddy04** [comment]
@ervintuzlic [Grid - Edit / Delete / Single Selection / Multi Selection](https://github.com/vikramlearning/blazorbootstrap-examples/blob/master/src/BlazorBootstrap.Examples/BlazorBootstrap.Examples/Pages/Employee/Employees.razor) version update. You can give a try and let me know, if you see any other issues. Feel free to create a new issue.
