### ISSUE TITLE
Tooltip does not disappear

### ISSUE THREAD

**Issue by Hunv** [vikramlearning/blazorbootstrap#213]
When using the tooltip like this and the Icon was clicked to follow the link, the tooltip stays even on the new page.

`<Tooltip Title="MyTitle" Placement="TooltipPlacement.Bottom"><a href="/mysubpage"><Icon Name="IconName.PlusSquare" Size="IconSize.x2" /></a></Tooltip>`

<img width="198" alt="image" src="https://github.com/vikramlearning/blazorbootstrap/assets/10775372/bc976255-e222-40d3-ade0-b3e1657f5f92">

Only refreshing the page with F5 removes the tooltip.

**Comment by gvreddy04** [comment]
@Hunv Please share the below information.

.NET Version:
BlazorBootstrap Version:
Blazor WebAssembly / Server:

**Comment by gvreddy04** [comment]
@drewcav96 There is no need to put button inside the Tooltip. But itself supports tooltip. 

https://demos.blazorbootstrap.com/buttons#show-tooltip

**Comment by gvreddy04** [comment]
@drewcav96 Please share a sample GitHub project to reproduce the issue.
