### ISSUE TITLE
Selection and filters both active bug

### ISSUE THREAD

**Issue by LucaCris** [vikramlearning/blazorbootstrap#214]
Filters are shifted by one position left when selection check-box (1.8.0 feature) is enabled:

![Screenshot 2023-05-29 164342](https://github.com/vikramlearning/blazorbootstrap/assets/50824617/ec77e7ee-0ac5-4098-a14c-95a738b104e6)

Severity: **TOP**

**Comment by gvreddy04** [comment]
![image](https://github.com/vikramlearning/blazorbootstrap/assets/2337067/027363dc-d293-4b12-8155-e0380e8dfc6f)

**Comment by superTeemo1** [comment]
I'm using single select functionality. When select item from grid and deselect it, item was not removed in code behind
