### ISSUE TITLE
blazorbootstrap control runing last  Render show code is html , I will run refresh then Control method ?I can't find method

### ISSUE THREAD

**Issue by Jockeyvb** [vikramlearning/blazorbootstrap#218]
for example：
` Markdig.Markdown.ToHtml ("<Tooltip Title='test' >test</Tooltip>");`
 

Tooltip  is blazorbootstrap control can Render  or reRegister Make it effective? 
  ```
private async void LoadData(){
 ....
blazorbootstrap.Current.Render ().....???
}
```

**Comment by gvreddy04** [comment]
@Jockeyvb Thank you for trying `BlazorBootstrap` components. I didn't get you.

Can you share the context here? Also, please share the GitHub repor with minimal repro code.

**Comment by Jockeyvb** [comment]
i was use tooltip ,by @code  create and use markdig component output  :` string s="<Tooltip Title='test' >test</Tooltip>";
<div>@Markdig.Markdown.ToHtml (s);</div>
`
and in razor page event:
`protected override Task OnAfterRenderAsync(bool firstRender)
    {
         
     .....BlazorBootstrap.Current.refresh()??

        return base.OnAfterRenderAsync(firstRender);
    }`
could have this method ?

**Comment by gvreddy04** [comment]
@Jockeyvb Are you expecting a Refresh method on `Tooltip` component?
