### ISSUE TITLE
HybridApp: Run on android 8.1 errors

### ISSUE THREAD

**Issue by Jockeyvb** [vikramlearning/blazorbootstrap#219]
![image](https://github.com/vikramlearning/blazorbootstrap/assets/16102290/ae33cce1-eec4-4b19-8bb9-529931f18e2d)

**Comment by Jockeyvb** [comment]
that GitHub repository have Including several projects under development. Have time to build another project and send it for testing.

The current issue is that I ran an error directly on Android device, so I cancelled using it

Is it BlazorHybrid App (Yes/No):　yes
.NET Version: .net 7.0
BlazorBootstrap Version: 1.8

**Comment by Jockeyvb** [comment]
I only want to implement the display function of bootstrap tooltip, which cannot be implemented with existing frameworks. I have written a JTip JavaScript script class myself to implement it. It can also run normally on Android 8.1 devices.

**Comment by gvreddy04** [comment]
@Jockeyvb We are able to run Blazor Hybrid applications with BlazorBootstrap. If you see any issues while using, feel free to create a new issue.
