### ISSUE TITLE
Modal Service

### ISSUE THREAD

**Issue by joselitogatchalianalonzo** [vikramlearning/blazorbootstrap#234]
Is there a way to invoke Modal as service same as ToastService? I want to invoke Modal located in MainLayout component from HttpInterceptorService which contains HttpClientInterceptor that handles API error globally. I want to display error code 500 internal server error message from a Modal declared in MainLayout.

**Comment by gvreddy04** [comment]
@joselitogatchalianalonzo We don't have at this moment. Will add in the next version.

**Comment by joselitogatchalianalonzo** [comment]
Thanks @gvreddy04 . That would be helpful in my projects.

**Comment by gvreddy04** [comment]
@joselitogatchalianalonzo We are adding a new section for all the services.

![image](https://github.com/vikramlearning/blazorbootstrap/assets/2337067/1cfca5b5-c18d-4b1d-ab27-316bb17b0cd1)
