### ISSUE TITLE
Grid: Freeze Header and First 2 Columns

### ISSUE THREAD

**Issue by joselitogatchalianalonzo** [vikramlearning/blazorbootstrap#246]
I'm using Grid Component in my Time Sheet List. Note: I set AllowPaging="false" because I just want to scroll vertically on the list. While scrolling, I want the Header to be visible always i.e. freeze regardless, how many rows are there on the list. Also, since there are many columns in my Time Sheet, I want the First 2 columns which in my case are Date and Employee Name to freeze while I'm scrolling horizontally to the right. How can I accomplish these 2 tasks? It would be great if you can provide sample code as you did before. Thanks in advance.

**Comment by joselitogatchalianalonzo** [comment]
@gvreddy04 Can I use CSS position:sticky for this as a work around? Can you give me sample code?

**Comment by gvreddy04** [comment]
@joselitogatchalianalonzo You can try using position: sticky. If you need a sample, I can provide one by 08/05/2023.

**Comment by joselitogatchalianalonzo** [comment]
Thanks @gvreddy04. I'm not proficient in CSS so it will be great if you can provide me the sample for position:sticky on both Header and first 2 grid columns by 08/05/2023.

**Comment by joselitogatchalianalonzo** [comment]
Hi @gvreddy04 A gentle follow-up regarding this issue

**Comment by joselitogatchalianalonzo** [comment]
Hi @gvreddy04. Among the components of Blazor Bootstrap, Grid is the most useful in most of my projects. I hope you could consider to line up this enhancement on your next version. Or at least if you could give me CSS as temporary work around, that would be great.

**Comment by gvreddy04** [comment]
@joselitogatchalianalonzo I'll share a temporary CSS ASAP.

**Comment by joselitogatchalianalonzo** [comment]
Thanks @gvreddy04. I'll just wait for the CSS.

**Comment by gvreddy04** [comment]
@joselitogatchalianalonzo Grid: Fixed Header Support #53

**Comment by gvreddy04** [comment]
@joselitogatchalianalonzo Fixed header feature is in-progress.

**Comment by gvreddy04** [comment]
@joselitogatchalianalonzo Just for your reference.


https://github.com/vikramlearning/blazorbootstrap/assets/2337067/8a9134a4-9d1e-4e03-865f-b7bef7cbeb58

**Comment by joselitogatchalianalonzo** [comment]
Thanks @gvreddy04. That's the enhancement I've been waiting for.  I hope you can also add fixed specified number of columns from left.

**Comment by gvreddy04** [comment]
#53
