### ISSUE TITLE
Grid Component: How to Invoke DataProvider from my own method?

### ISSUE THREAD

**Issue by joselitogatchalianalonzo** [vikramlearning/blazorbootstrap#251]
I'm filling the Grid with Time Sheet records from back-end API based on specified Date Range, for example June 1, 2023 to June 15, 2023 . Note: I set AllowPaging="false". Based on my own observation, DataProvider method is being invoked on initial loading of Grid. Let's say I want to get again another set of Time Sheet records with different date range for example June 16, 2023 to June 29, 2023, how can I invoke the Data Provider method from my own Search Button during onclick event? Note: I also set AllowFiltering="false".

**Comment by gvreddy04** [comment]
@joselitogatchalianalonzo Use `Data` parameter to assign the collection.

Check the below links:

1. https://demos.blazorbootstrap.com/grid#data-parameter-assign-collection
1. https://demos.blazorbootstrap.com/grid#data-parameter-update-collection

**Comment by joselitogatchalianalonzo** [comment]
Thanks @gvreddy04 .
