### ISSUE TITLE
Issue with new ModalService

### ISSUE THREAD

**Issue by MarvinKlein1508** [vikramlearning/blazorbootstrap#258]
There are two issues with the new `ModalService`

## First issue
On first start it only works once, then you'll need to refresh the page in order for it to work fully.

To reproduce:
1. Clone repository
2. Set BlazorBootstrap.Demo.Server as startup project
3. Click on Modals
4. Click on Service => ModalService
5. Launch modal
6. Try to open a second modal
7. Refresh the page and launch modal
8. try to launch another modal

## Second issue
The modals are hanging behind on your preview site. Take a look on this GIF. I wasn't able to reproduce this on my local machine on both Server Blazor and WebAssembly.
![modalservice](https://github.com/vikramlearning/blazorbootstrap/assets/32510006/53e07c30-3d2d-4561-8f38-1b26edeffd9d)

**Comment by gvreddy04** [comment]
@MarvinKlein1508 Can you share more details on the second issue. I didn't get you the scenario.

**Comment by MarvinKlein1508** [comment]
@gvreddy04 as you can see in the GIF the styling gets applied to the modal after it has been rendered. It gets more clear when you use different positioning. However this behaviour only applies to your hosted demo site. When I run both Blazor Server and WebAssembly apps on my local machine I didn't have this issue.

**Comment by MarvinKlein1508** [comment]
In the GIF you can see for example the header changes color after the animation.
