### ISSUE TITLE
ToastService not working anymore in version 1.9.1

### ISSUE THREAD

**Issue by joselitogatchalianalonzo** [vikramlearning/blazorbootstrap#261]
I'm using ToastService and below are some fragments in my code:

In MainLayout:
Toasts class="p-3" Delay="3000" Placement="ToastsPlacement.TopCenter" 

In my component invoking ToastService:
var toastMsg = new ToastMessage
			{
			  Type = ToastType.Danger,
			  Message = "Something went wrong. Please contact your administrator",
			 AutoHide = false
		       };                    
  _toastService.Notify(toastMsg);

Above code does not work anymore in 1.9.1. Toast Message is not being displayed at the time I called  _toastService.Notify method. Note: Above code works in 1.8.3 except for AutoHide property which only became available in 1.9.0 and 1.9.1

Additional information: ToastMessage of above code will be displayed, when I navigate to other page. In other words, the message is delayed. This is not the case in 1.8.3. 

Is this a bug or I'm missing something here?

**Comment by gvreddy04** [comment]
@joselitogatchalianalonzo We made a minor fix, but I have a suggestion regarding the usage of services on the landing page. Currently, the landing page is not using the MainLayout; instead, it is using the EmptyLayout. Therefore, I recommend testing the services on a specific page.

**Comment by joselitogatchalianalonzo** [comment]
Thanks @gvreddy04
