### ISSUE TITLE
Grid Component: Error encountered in grid.RefreshDataAsync()

### ISSUE THREAD

**Issue by joselitogatchalianalonzo** [vikramlearning/blazorbootstrap#263]
I'm trying to refresh the grid with the time sheets record from back-end API using Data parameter. Below are some fragments of my code.

//Initialize the Grid
Grid TimeSheet grid;  //Note: TimeSheet is enclosed in <>. it does not appear here.
....
....

private async Task RefreshTimeSheet(DateTime startDate, DateTime startDate)
{
  //Note: timeSheets is the Data parameter of the Grid
  timeSheets = await GetTimeSheetsAsync(0);
  await grid.RefreshDataAsync();
}

When I called RefreshTimeSheet method, I'm encountering error: "Unhandled exception rendering component: The render handle is not yet assigned".

Kindly let me know what's wrong with my code.

**Comment by gvreddy04** [comment]
@joselitogatchalianalonzo Can you share a sample GitHub repo to reproduce the issue?

**Comment by joselitogatchalianalonzo** [comment]
@gvreddy04 I was able to find out the cause of the error. I forgot to put <Grid @ref="grid" in my razor file. So the error has gone. However. The grid is still empty after calling RefreshDataAsync().
![Empty](https://github.com/vikramlearning/blazorbootstrap/assets/68423158/605543e1-e2e1-4a95-835b-094b980d4ebd)

**Comment by joselitogatchalianalonzo** [comment]
@gvreddy04 Finally, I was able to resolve the issue by below code:
private async Task RefreshTimeSheet(DateTime startDate, DateTime endDate)
{
//Note: timeSheets is the Data parameter of the Grid
var ts = await GetTimeSheetsAsync(startDate, endDate);
timeSheets.AddRange(ts);
await grid.RefreshDataAsync();
}

Basically I assigned the returned result of API to a temporarily variable ts and Add it to Data Parameter timeSheets by AddRange method. Is that the right way to do it?
