### ISSUE TITLE
Grid Component: Row Click Event

### ISSUE THREAD

**Issue by joselitogatchalianalonzo** [vikramlearning/blazorbootstrap#264]
I want to use Grid together with Modal to create Pop-up search component for Employees. After filtering the name to be searched, user will click on any column of the row of employee selected. Upon clicking of row, I will pass the selected row to the parent component in order to display the details of selected employee. How can I accomplish this task? Note: I'm aware that there is selection column when you set AllowSelection="true" in Grid. However, I think it would be a better user experience if you can click on any column of the selected row so there should be an event for Row Click. I'm not sure if it is available and how to invoke it.

**Comment by gvreddy04** [comment]
@joselitogatchalianalonzo We can achive this easily.

```cshtml
<Grid TItem="Student"
      Class="table table-hover table-bordered table-striped"
      DataProvider="StudentsDataProvider"
      AllowPaging="true"
      PaginationAlignment="Alignment.End"
      PageSize="15">

    <GridColumn TItem="Student" Context="student" HeaderText="Student">
        @student.StudentName
    </GridColumn>

    <GridColumn TItem="Student" Context="student" HeaderText="Parent / Gaurdian">
        @student.GaurdianName
    </GridColumn>

    <GridColumn TItem="Student" Context="student" HeaderText="DOB">
        @student.DOB.ToString("dd/MMM/yyyy")
    </GridColumn>

    <GridColumn TItem="Student" Context="student" HeaderText="Email">
        @(student.Email ?? "-")
    </GridColumn>

    <GridColumn TItem="Student" Context="student" HeaderText="Phone Number">
        +@student.CountryCode @student.PhoneNumber
    </GridColumn>

    <GridColumn TItem="Student" Context="student" HeaderText="Student">
        <Button Color="ButtonColor.Primary" @onclick="((args) => OnClickWithArgs(args, student))"> Details </Button>
    </GridColumn>

</Grid>
```
```cs
@code {
    public string message = "Test message";

    protected void OnClickWithArgs(EventArgs args, Student student)
    {
        // show offcanvas
        // other stuff
    }
}
```
Note: There could be typos.

**Comment by joselitogatchalianalonzo** [comment]
Thanks @gvreddy04 . Based on my understanding, there is an Action column which contains button that the user will click in order to display the details of student. However, what I'm looking for is Row Click event on the whole row. i.e. user will click on any column of the row not just 1 specific button column. Since it is a pop-up search, I want the user to select the row faster by clicking on any column of the row.
