### ISSUE TITLE
Sidebar: Sidebar should close automatically on mobile

### ISSUE THREAD

**Issue by MarvinKlein1508** [vikramlearning/blazorbootstrap#274]
**Describe the bug**
When clicking on an last level item the sidebar should be closed automatically on mobile devices.

**To Reproduce**
1. Launch any mobile browser
2. Open menu and select any nav item

**Expected behavior**
The sidebar should automatically close when I select an item which triggers a navigation.

**Screenshots**
![sidebar](https://github.com/vikramlearning/blazorbootstrap/assets/32510006/c1642a36-5642-4e24-8a8f-cedefb86b407)

**Comment by MarvinKlein1508** [comment]
Any update on this?

**Comment by MarvinKlein1508** [comment]
@gvreddy04 you have any plans on implementing this?

**Comment by gvreddy04** [comment]
@MarvinKlein1508 I'll include this in the next release.

**Comment by SistemasPulpo** [comment]
Vikram excellent work! How can I perform an onclick in the Navitem to call an offcanvas?
