### ISSUE TITLE
Grid Component - Translatable page size selector

### ISSUE THREAD

**Issue by JanTamis** [vikramlearning/blazorbootstrap#285]
please let us translate the page size selector 
![image](https://github.com/vikramlearning/blazorbootstrap/assets/73336709/27040aa3-8494-46fc-8b76-d41628af37ca)

**Comment by gvreddy04** [comment]
@JanTamis Sample for your reference.

![image](https://github.com/vikramlearning/blazorbootstrap/assets/2337067/02635ff7-e101-40b0-9ce5-c393109c4a50)

**Comment by JanTamis** [comment]
Thank you so much!
