### ISSUE TITLE
Grid: Add defaults for expected values

### ISSUE THREAD

**Issue by LucaCris** [vikramlearning/blazorbootstrap#293]
Grid component, 1.9.5 (and previous).

Even if not used, these params must be set for every Grid in the code:

![Screenshot 2023-07-17 121255](https://github.com/vikramlearning/blazorbootstrap/assets/50824617/6cdb6c24-2d07-45b1-908e-db79b1525983)

Otherwise a lot of warnings are issued, like:

```
warning RZ2012: Component 'Grid' expects a value for the parameter 'PageSizeSelectorItems', but a value may not have been provided.
warning RZ2012: Component 'Grid' expects a value for the parameter 'PaginationItemsTextFormat', but a value may not have been provided.
warning RZ2012: Component 'Grid' expects a value for the parameter 'ItemsPerPageText', but a value may not have been provided.

```
(and the razor code is green underlined)

Please set an _empty_ default, for who doesn't need them...

**Comment by gvreddy04** [comment]
@LucaCris We assigned the default values, but we still see those warnings due to **EditorRequired**. I will handle this differently then.

```cs
[Parameter, EditorRequired] public string ItemsPerPageText { get; set; } = "Items per page";

[Parameter, EditorRequired] public string PaginationItemsTextFormat { get; set; } = "{0} - {1} of {2} items";
```

**Comment by gvreddy04** [comment]
@LucaCris This is abug in the Visual Studio. This will be fixed in the upcoming versions.

[Consider `@bind` for EditorRequired parameters #8337](https://github.com/dotnet/razor/pull/8337)
