### ISSUE TITLE
Tabs: Disabled tabs are not activated after ShowTab*-request

### ISSUE THREAD

**Issue by Capellio** [vikramlearning/blazorbootstrap#303]
I use the tabs for a wizard like setup. 
All but the first tabs are set disabled.

when the first tab is completed i would like to go to the next one, I use the method "ShowTabByNameAsync" which calles "ShowTabAsync" => unless the tab is disabled.

so I have to enable the tab first which would be great if this can be done through the Tabs component itself (which is not possible at the moment). Now I fixed this by using a property (Disabled="@(!ContractRulesEnabled)") on the tab.

the problem with this is notifying the component that something has changed, so we call "StateHasChanged" and then calling ShowTabByNameAsync works. the content of the tab is shown. unfortunately the "active" class is not set in this way, so we call again the StateHasChanged and again the ShowTabByNameAsync and the all is fine.
![image](https://github.com/vikramlearning/blazorbootstrap/assets/15339971/d9554c9e-3656-4917-866d-b2523372ed7d)

It would be nicer to do all within a single call. perhaps creating a EnableAndShowTabByNameAsync method?
Also it would be nice if you can access the individual tabs from the Tabs-component.

**Comment by gvreddy04** [comment]
@Capellio Can you share a GitHub repo with minimal code to understand your scenario.

**Comment by gvreddy04** [comment]
@Capellio I'm closing this for now due to inactivity. If you see any issues, please creat a new one.
