### ISSUE TITLE
Grid: Set Row Height and Text Size 

### ISSUE THREAD

**Issue by joselitogatchalianalonzo** [vikramlearning/blazorbootstrap#316]
I want to set the height of each row in the Grid and also the text size to smaller size so I can display more rows without scrolling.  How can I accomplish this task?

**Comment by gvreddy04** [comment]
@joselitogatchalianalonzo This can be achieved by using **Conditional css class for grid row** feature.

Link: https://demos.blazorbootstrap.com/grid#conditional-css-class-for-grid-row

### Sample Code:

```cshtml
<Grid TItem="Employee1"
      AllowFiltering="true"
      AllowPaging="true"
      AllowSorting="true"
      Class="table table-hover table-bordered"
      DataProvider="EmployeesDataProvider"
      PageSize="5"
      Responsive="true"
      RowClass="@(x => "custom-row-height-font-size")">

      . . . 

</Grid>
.
.
.
```


### Screenshots:

**Before:**

![image](https://github.com/vikramlearning/blazorbootstrap/assets/2337067/667a85a8-141f-43d0-90d0-d83af011f8dc)

**After:**

![image](https://github.com/vikramlearning/blazorbootstrap/assets/2337067/320128e5-8a34-4a1d-8564-ddc4d77cd753)
