### ISSUE TITLE
Chart: Add Chart Data Labels

### ISSUE THREAD

**Issue by LukasHKlg** [vikramlearning/blazorbootstrap#317]
This is a feature request to make it possible to show the number above the bar. For example:

![image](https://github.com/vikramlearning/blazorbootstrap/assets/110227200/780b3e7f-8ffb-48e1-82aa-a4836189f5fa)

This is already an available plugin for chart.js. Its called chartjs-plugin-datalabels. You can see it with the code here: https://chartjs-plugin-datalabels.netlify.app/samples/charts/bar.html

It would be awesome if the text could be changed where to be aligned like in center or start or end.

**Comment by LukasHKlg** [comment]
Thanks for adding this feature.

Haven't found it in the docu, is there a way to change the background color for the datalabels? The problem I have is that the datalabels are always rendered even if the data is 0. And i dont want a background color when the labels are shown above the bar as aligned "end" and anchor also set to "end".

I figured out a way to only set the value if the value is bigger than 0 otherwise take null, when null the datalabel doesn't seem to be rendered which is what I needed. The way i achieved this with javascript:

Chart.defaults.set('plugins.datalabels', {
    formatter: (value) => {
        return value > 0 ? value : null;
    },
})

FYI as far as i know this sets the same settings for all charts in the application.

**Comment by LukasHKlg** [comment]
I did not find this in your documentation:


<script src="https://cdnjs.cloudflare.com/ajax/libs/chartjs-plugin-datalabels/2.2.0/chartjs-plugin-datalabels.min.js" integrity="sha512-JPcRR8yFa8mmCsfrw4TNte1ZvF1e3+1SdGMslZvmrzDYxS69J7J49vkFL8u6u8PlPJK+H3voElBtUCzaXj+6ig==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>

But i found it in your github commit. You should maybe add this to the documentation.

**Comment by gvreddy04** [comment]
@LukasHKlg I will fix the documentation. Thank you.

We covered this in the demos.
Link: https://demos.blazorbootstrap.com/getting-started/blazor-webassembly#add-script-references
