### ISSUE TITLE
NavItem not selected if query parameters are used

### ISSUE THREAD

**Issue by mdeppe42** [vikramlearning/blazorbootstrap#322]
**Describe the bug**
The indication of the active page in the NavBar (Item is bold and has different background color) does not work, if query parameters are added to the Url.

**To Reproduce**
1. Create a "Foo" NavItem for the NavBar with Href = "/foo"
2. Click on item "Foo" -> Foo page is opened and Foo item in NavBar is printed bold
3. Add a query parameter to the Url, e.g. /foo/1 or /foo?bar=true
4. Foo item in the NavBar is not selected any more

**Expected behavior**
I expected that the item is still shown as selected even if parameters are added to the Url.
I suggest adding a property to NavItem to enable a "catch all" behavior. 
Then you could decide if for example /foo, /foo/1, /foo/2 and /foo?bar=true are
1. considered as the same page
2. considered as different pages

**Comment by MarvinKlein1508** [comment]
I'm running on 1.10 and I don't have this issue.

![grafik](https://github.com/vikramlearning/blazorbootstrap/assets/32510006/15d0b536-49a0-4e54-a797-861133345bc4)

My NavItem is specified like this:
```csharp
yield return new NavItem
{
    Id = "nav-admin",
    IconName = IconName.Gear,
    Text = "Administration",
    IconColor = IconColor.Success,
    Match = NavLinkMatch.All
};

yield return new NavItem
{
    Id = "nav-admin-users",
    Href = "/Admin/Users",
    IconName = IconName.PeopleFill,
    Text = "Benutzerverwaltung",
    ParentId = "nav-admin"
};

```

**Comment by gvreddy04** [comment]
@MarvinKlein1508 Thank you for validating this issue.

**Comment by gvreddy04** [comment]
@mdeppe42 Please re-validate this issue and let us know.

**Comment by mdeppe42** [comment]
@MarvinKlein1508 Thank you. Seems that I misunderstood how the
