### ISSUE TITLE
It looks like ModalService.ShowAsync(modalOption) will not wait the modal window button to be pressed !

### ISSUE THREAD

**Issue by sailman342** [vikramlearning/blazorbootstrap#325]
Using version 1.10.0 of blazor.bootstrap which is a wonderfull piece of code by the way, I don't succeed to display a modal message and wait user confirmation before navigating to another page !

    public async Task Annuler()  // from cancel button
    {
        await ShowModal(ModalType.Primary, "Annulation", "Retour à la liste des utilisateurs du site"); // will work if last statement
        await sessionStorage.SetItemAsync<uint>("PersonToCareAbout", 0); // Uncomment to get it showing
        NavigationManager.NavigateTo("/siteuserslist", forceLoad: true, replace: true); // Uncomment to get it showing
    }

    public async Task ShowModal(ModalType modalType, string title, string message)
    {
        ModalOption modalOption = new ModalOption
            {
                Title = title,
                Message = message,
                Type = modalType,
            };

        await ModalService.ShowAsync(modalOption);
    }

If I comment the two last statements of Task Annuler (Event of a Cancel button), the modal window will show up.

Otherwise the code will go through and navigate to the siteuserslist page !

What am I doing wrong ? Thanks for your help !

**Comment by gvreddy04** [comment]
@sailman342 

To implement this scenario, use the **Confirm Dialog**. In the Confirm Dialog, you can display a **Dynamic component**.

![image](https://github.com/vikramlearning/blazorbootstrap/assets/2337067/fffecbb4-cb2b-47e1-8f5f-3629ba2fa4cf)

**Link:** https://demos.blazorbootstrap.com/confirm-dialog#dynamic-component-as-confirm-dialog

**Sample Code:**

```cshtml
<ConfirmDialog @ref="dialog" />

<Button Color="ButtonColor.Danger" @onclick="DeleteEmployeeAsync"> Delete Employee </Button>

@code {
    private ConfirmDialog dialog;

    [Inject] ToastService ToastService { get; set; }

    private async Task DeleteEmployeeAsync()
    {
        var parameters = new Dictionary<string, object>();
        parameters.Add("EmployeeId", 321);

        var confirmation = await dialog.ShowAsync<EmployeeDemoComponent>("Are you sure you want to delete this employee?", parameters);

        if (confirmation)
        {
            // call API to delete the employee
            // show acknowledgment to the user
            ToastService.Notify(new ToastMessage(ToastType.Success, $"Employee deleted successfully."));
        }
        else
            ToastService.Notify(new ToastMessage(ToastType.Secondary, $"Delete action canceled."));
    }
}
```

**Comment by sailman342** [comment]
Thank you for your advice but it imposes to have some code in the HTML part of the razor page, This is not suitable to implement the modal alert in a library then ... but I used the modal component somewhere else and it works fine, I will use it as a work around for the time being.

I downloaded the latest state of the master branch and searched differences between your implementation and mine (program.cs, layout ...) and I could not find anything relevant!

Endly I modified your demo code as follow and the modal window will not show up either (tested on .Net 6 and .Net 7)

```
@code {
    [Inject] ModalService ModalService { get; set; } = default!;
    [Inject] NavigationManager NavigationManager { get; set; } = default!;

    private async Task ShowModal(ModalType modalType)
    {
        var modalOption = new ModalOption
                          {
                              Title = "Modal title",
                              Message = "Modal body text goes here.",
                              Type = modalType,
                          };

        await ModalService.ShowAsync(modalOption);

        NavigationManager.NavigateTo("/", forceLoad: true, replace: true); // Uncomment to get it showing
    }
}
```

**Comment by sailman342** [comment]
Endly I used the confirm component setting the no button label to "" and it works like a modal windows waiting the yes button to be clicked !

Maybe a nice feature to document (if not done yet ?)

Thanks, you can close if you whish

**Comment by gvreddy04** [comment]
@sailman342 We are adding callback feature to modal service showAsync method. 

```cshtml
<Button Color="ButtonColor.Primary" @onclick="() => ShowModal(ModalSize.Regular)">Show Modal</Button>

<div class="mt-3">
    @callbackActionMessage
</div>

@code {

    [Inject] ModalService ModalService { get; set; } = default!;

    private string callbackActionMessage = "";

    private async Task ShowModal(ModalSize modalSize)
    {
        var modalOption = new ModalOption
                          {
                              Title = "Modal title",
                              Message = "Modal body text goes here.",
                              Size = modalSize
                          };

        await ModalService.ShowAsync(modalOption, OnModalClose);
    }

    private void OnModalClose()
    {
        // TODO: Do operations required after modal close.
        callbackActionMessage = $"Modal closed at {DateTime.Now}";

        StateHasChanged();
    }
}
```

**Comment by sailman342** [comment]
Thank you but using Confirm with a single button works like a charm :-) The wait is working OK :-) 

But thanks a lot !

Would you be interested on a clue to make a component "save data in user selected folder and filename ? This is definitively missing in Blazor, all proposed solutions save to download folder :-( If yes tell me I will provide you some code :-)

Nice wok !
