### ISSUE TITLE
Tooltip problem continues

### ISSUE THREAD

**Issue by LucaCris** [vikramlearning/blazorbootstrap#327]
1.10.0, WASM.

If a button has a tooltip, and pressing it the page content changes (making button disappear), the tooltip remains stucked. Also many times!

![Screenshot 2023-08-21 160502](https://github.com/vikramlearning/blazorbootstrap/assets/50824617/c693f152-08c8-4358-ab70-fa646ce5e692)

**Comment by gvreddy04** [comment]
@LucaCris There is a known issue when an **<a>** tag is placed inside a tooltip. Can you share the sample code or GitHub repository you are using in your scenario?

**Comment by LucaCris** [comment]
Check the second Button, with tooltip:
```
        <GridColumn TItem="Entity" HeaderText="Edit">
            <Button @onclick="()=>OnEdit(context)" Size="Size.Small"><Icon Name="IconName.PencilSquare" /></Button>
            <Button @onclick="()=>OnEditList(context)" Size="Size.Small" TooltipTitle="test"><Icon Name="IconName.ListOl" /></Button>
            <Button @onclick="()=>OnEditForm(context)" Size="Size.Small"><Icon Name="IconName.InputCursorText" /></Button>
        </GridColumn>
```
The OnEditList() will remove actual grid and another one will be displayed, but the tooltip from firing button remains forever.

**Comment by MarvinKlein1508** [comment]
@gvreddy04 I've created a small repository which showcases this issue. The issue happens on all three buttons in Index.razor

https://github.com/MarvinKlein1508/TooltipDemo

**Comment by MarvinKlein1508** [comment]
![grafik](https://github.com/vikramlearning/blazorbootstrap/assets/32510006/15a0302e-b1db-446b-b46b-ed250e54a6bc)

**Comment by MarvinKlein1508** [comment]
@gvreddy04 any update on this? This bug is really annoying.
