### ISSUE TITLE
DateInput problem with keyboard

### ISSUE THREAD

**Issue by LucaCris** [vikramlearning/blazorbootstrap#340]
1.10.1 (Latest) on WebAssembly project.

Have a DateInput and enter date, for example "today":

![immagine](https://github.com/vikramlearning/blazorbootstrap/assets/50824617/6144fb5a-f6c5-4c42-a0d6-08a9891304bd)

Now try to manually edit with keyboard only the month... [BUG]: day and year fileds are _reset_ on value changed event:

![immagine](https://github.com/vikramlearning/blazorbootstrap/assets/50824617/6a4e33bd-4ac7-4af6-89fa-06e76712d916)

**Comment by gvreddy04** [comment]
@LucaCris Were you able to replicate here: https://demos.getblazorbootstrap.com/form/date-input#validations

Please specify the DataType of the DateInput. If possible share a full screenshot of the DevTools, in case of any console errors.

**Comment by LucaCris** [comment]
I can't tell to all my customers to do something non-standard. If I have two digit template "08" is the only right input sequence.

Replicated also in demo site... definitely a bug. 🙂

**Comment by MarvinKlein1508** [comment]
@gvreddy04 the issue is fixed when you wrap the `SetValueAsync` call in an if statement.
```csharp
if (e.Value is string test && test != string.Empty)
```

BTW. could you help me understand what the purpose is of this component? Blazor already allows you to todo all this with the native `InputDate` component. Where is the main benefit of using this component instead?

**Comment by LucaCris** [comment]
Can we have a fix for the "clear to null value" in DateTime? object?

**Comment by MarvinKlein1508** [comment]
I gonna take a look on it this week. Maybe I find a solution
