### ISSUE TITLE
Sizing for icons in buttons is strange

### ISSUE THREAD

**Issue by MarvinKlein1508** [vikramlearning/blazorbootstrap#346]
**Describe the bug**
When using icons in buttons they look kinda strange in all sizes besides x5. For many icons you can barely see the icon itself. 

For this reason I'm using always `IconSize.x5` which results in more type work.

![grafik](https://github.com/vikramlearning/blazorbootstrap/assets/32510006/3a054852-49ca-40c7-9cd4-c3aa9c601cb5)

Maybe there should be a way to set the default iconsize for everything.

**Comment by gvreddy04** [comment]
@MarvinKlein1508 Could you share a sample code for the above screenshot? It would be better for my understanding.

**Comment by MarvinKlein1508** [comment]
For this case it is:
```csharp
<Button Color="ButtonColor.Success">
    <Icon Name="IconName.Plus" Size="IconSize.None" />
</Button>

<Button Color="ButtonColor.Success">
    <Icon Name="IconName.Plus" Size="IconSize.x2" />
</Button>

<Button Color="ButtonColor.Success">
    <Icon Name="IconName.Plus" Size="IconSize.x3" />
</Button>

<Button Color="ButtonColor.Success">
    <Icon Name="IconName.Plus" Size="IconSize.x4" />
</Button>

<Button Color="ButtonColor.Success">
    <Icon Name="IconName.Plus" Size="IconSize.x5" />
</Button>
```

When using any other icon library like fontawesome for example the output will look the 4th or second button. The option `IconSize.None` (which is the default) always results in buttons with to small icons which you can barely see. IMO the default should be either `x4` or `x5`. Maybe even an option to set the default size so you don't need to specify it over and over again.

I also don't get why x5 is smaller than x4. Should it grow with a larger x amount?

**Comment by gvreddy04** [comment]
@MarvinKlein1508 Thank you. I'll check this.
