### ISSUE TITLE
Autocomplete shows "No Records Found" Before Search is finished?

### ISSUE THREAD

**Issue by chobo2** [vikramlearning/blazorbootstrap#352]
Hi

I am trying to use the Autocomplete and even when I look at your ["Server side data" ](https://demos.blazorbootstrap.com/autocomplete)example I noticed if I for instance type in "p" it will first show "no records found" then I see the search progress circle go and then it find results.

Why does it display "no records found" first before a search is finished?

Also when I go into the "code" portion of the sample it would be great to see what 

customerService.GetCustomersAsync(request.Filter, request.CancellationToken);

actually has in the method, so I can see what was done. I tried looking into the code on github here but I don't even see any code for "auto complete"

**Comment by gvreddy04** [comment]
@chobo2 We are adding `Loading...` text.

**Comment by chobo2** [comment]
Cool, loading would be good to have.
