### ISSUE TITLE
Update bootstrap icons to v1.11

### ISSUE THREAD

**Issue by MarvinKlein1508** [vikramlearning/blazorbootstrap#359]
There is another major update for bootstrap icons which adds many icons I was still missing like save and copy.

It would be great if you can update the libarry to use the latest icons.
https://blog.getbootstrap.com//2023/09/12/bootstrap-icons-1-11-0/

**Comment by gvreddy04** [comment]
@MarvinKlein1508 Added part of #357.

**Comment by MarvinKlein1508** [comment]
Thanks a lot! Can't wait for the new update with all the latest fixes and features :)
