### ISSUE TITLE
Add feature to disable Dropdown

### ISSUE THREAD

**Issue by powertec-dan** [vikramlearning/blazorbootstrap#373]
Currently there is no nice way to disable the Dropdown control, only disable items within the dropdown list.

It would be good to be able to disable the entire control.

**Comment by gvreddy04** [comment]
@powertec-dan As an interim solution, please add an HTML disable attribute to the toggle button.

## Example:

```cshtml
<Dropdown>
    <DropdownToggleButton Color="ButtonColor.Secondary" disabled="@disabled">Dropdown button</DropdownToggleButton>
    <DropdownMenu>
        <DropdownItem To="#" Type="ButtonType.Link">Action</DropdownItem>
        <DropdownItem To="#" Type="ButtonType.Link">Another action</DropdownItem>
        <DropdownItem To="#" Type="ButtonType.Link">Something else here</DropdownItem>
    </DropdownMenu>
</Dropdown>

@code
{
    private bool disabled = true;
}
```

## Screenshot:

![image](https://github.com/vikramlearning/blazorbootstrap/assets/2337067/d37241d4-e753-45c5-9221-12fbe96ee35c)

**Comment by gvreddy04** [comment]
Refer: https://github.com/vikramlearning/blazorbootstrap/discussions/371
