### ISSUE TITLE
Grid: Ability to add Row Detail View for a row

### ISSUE THREAD

**Issue by aditya119** [vikramlearning/blazorbootstrap#374]
Is it possible to display row details in the grid?
A way to expand the row and display its details below that.

Something like: [Mud Blazor](https://mudblazor.com/components/datagrid#row-detail-view)

**Comment by gvreddy04** [comment]
@aditya119 Right now, row detail view is not supported. We can do an enhancement in the future.

For now, I can recommend three options:

1. Row click event -> show modal/offcanvas
2. Row double-click event -> show modal/offcanvas
3. Add an action icon/button column to each row -> show modal/offcanvas

**Comment by aditya119** [comment]
Ok. Thanks.

**Comment by LucaCris** [comment]
My current solution:

#> Row 1
#> Row 2
#> Row 3
#> Row 4

I press the Row 3 "detail button" and I show

#> Row3
---  Detail Row 1
---  Detail Row 2
---  Detail Row 2

And a "back button" to return to initial state.

So the main table is filtered for the active item only, and a new hidden/temporary table appears below.
