### ISSUE TITLE
Typo in documentation

### ISSUE THREAD

**Issue by Lucasharskamp** [vikramlearning/blazorbootstrap#392]
**Describe the bug**
[Progress page in documentation](https://docs.blazorbootstrap.com/components/progress
) Shows the word ''description'' as ''Descritpion'' multiple times

**To Reproduce**
Go to page

**Expected behavior**
-
**Screenshots**
![image](https://github.com/vikramlearning/blazorbootstrap/assets/50183941/636e36e0-12b7-4628-8361-67d16c7d2c61)

**Versions (please complete the following information):**
-
**Sample code**
-
**GitHub repo**
-
**Desktop (please complete the following information):**
-

**Smartphone (please complete the following information):**
-

**Additional context**
-

**Comment by gvreddy04** [comment]
@Lucasharskamp If you have some time, please create a PR. That will be of great help.
