### ISSUE TITLE
Switch: Double click on switch selects the label

### ISSUE THREAD

**Issue by MarvinKlein1508** [vikramlearning/blazorbootstrap#401]
**Describe the bug**
When you double click a switch button, the webbrowser selects the entire label text

**To Reproduce**
Create any switch with a label and click twice on the switch button.

**Expected behavior**
The label should not be selected

**Screenshots**
![switch_highlight](https://github.com/vikramlearning/blazorbootstrap/assets/32510006/61674b68-14e0-4b36-aa2a-1c6f23e622b1)

**Versions (please complete the following information):**
 - BlazorBootstrap: 1.10.2
 - Blazor Server
 - .NET Version: .NET 7

**Comment by gvreddy04** [comment]
@MarvinKlein1508 I'm not able to reproduce this unless I click only on the label. Can you share the sample code?


https://github.com/vikramlearning/blazorbootstrap/assets/2337067/130de443-7511-4eee-ab81-05335d6e5321

**Comment by MarvinKlein1508** [comment]
Hi @gvreddy04 

I have the same on the demo page.
https://demos.blazorbootstrap.com/form/switch

This seems to be related to Firefox. In Chrome it works fine.

**Comment by MarvinKlein1508** [comment]
I've investigated this further. It seems like it has something todo with trimming the whitespace. Since .NET 5 Blazor trimms all whitespace by default.

https://github.com/aspnet/Announcements/issues/426

Adding `@preservewhitespace true` to the component fixes this issue. Looks like the trimmed whitespace is used for something here.

I will open a PR shortly.
