### ISSUE TITLE
GridSettings does not set the pager to the correct page

### ISSUE THREAD

**Issue by patricq** [vikramlearning/blazorbootstrap#412]
Bootstrap: 5.3.1
BlazorBootstrap: 1.10.3
.NET: 7.0

When I restore GridSettings the selected page of the grid is displayed but the pager itself stays on Page 1 instead of the correct page.

Steps:

Navigate grid to page 2
Use OnGridSettingsChanged to save the state of the grid (pagenumber)
Leave the page with the grid on it and navigate back to it.
Use GridSettingsProvider to set settings.PageNumber to 2

Result: The data in the grid is the correct data for page 2. The pager itself stays on page 1.

If anything is unclear then let me know (first time I used GitHub to open a issue like this ;) )

**Comment by gvreddy04** [comment]
@patricq Thank you for trying the BlazorBootstrap. I'm not able to reproduce the issue. Please see the attached video for your reference. Please share the code or GitHub repo to reproduce the issue with minimal steps.


https://github.com/vikramlearning/blazorbootstrap/assets/2337067/b77757f8-e9ef-4cd6-bb01-7869274cb2cf

**Comment by patricq** [comment]
Yes I see my error now. I used ResetPageNumber to refresh the data in the grid, this causes the pager to select page 1.
I have changed it now and it works perfectly.

Thanx!

**Comment by patricq** [comment]
This can be closed.
