### ISSUE TITLE
Doc issue

### ISSUE THREAD

**Issue by LucaCris** [vikramlearning/blazorbootstrap#413]
As described here...

> ![immagine](https://github.com/vikramlearning/blazorbootstrap/assets/50824617/a0c9473b-7b98-4406-b411-10ece6964c6e)

...removing **app.css** will break standard Blazor startup hour-glass.

**Comment by gvreddy04** [comment]
@LucaCris  I'm validating this right now.

Please share the below details:

1.  .NET 6 / .NET 7
2. Blazor Web Assembly / Server
3. BlazorBootstrap version

**Comment by LucaCris** [comment]
NET 7 / WASM / Latest BB (but also previous).
