### ISSUE TITLE
Pressing Esc still closes the modal even with UseStaticBackdrop="true"

### ISSUE THREAD

**Issue by NhanNTWPV** [vikramlearning/blazorbootstrap#416]
**Describe the bug**
When setting UseStaticBackdrop="true", user is still able to close the modal by pressing Esc

**Expected behavior**
The modal does not close upon pressing Esc as described in the docs.

**Versions (please complete the following information):**
 - BlazorBootstrap: 1.10.3
 - Blazor WebAssembly / Server: Server
 - .NET Version: 7

**Comment by NhanNTWPV** [comment]
@gvreddy04 This seems to stem from `CloseOnEscape` being set to true by default. The current behaviour does not conform to [the original Bootstrap one](https://getbootstrap.com/docs/5.0/components/modal/#static-backdrop). Should we assign it to false when `UseStaticBackdrop` equals true?

**Comment by gvreddy04** [comment]
@NhanNTWPV Yes, you are correct. Set **CloseOnEscape** to **false** when **UseStaticBackdrop** is **true**.

**Example:**

```cshtml
<Modal @ref="modal" title="Modal title" UseStaticBackdrop="true" CloseOnEscape="false">
    <BodyTemplate>
        I will not close if you click outside me. Don't even try to press escape key.
    </BodyTemplate>
    <FooterTemplate>
        <Button Color="ButtonColor.Secondary" @onclick="OnHideModalClick">Close</Button>
        <Button Color="ButtonColor.Primary">Understood</Button>
    </FooterTemplate>
</Modal>

<Button Color="ButtonColor.Primary" @onclick="OnShowModalClick">Launch static backdrop modal</Button>

@code {
    private Modal modal = default!;

    private async Task OnShowModalClick()
    {
        await modal.ShowAsync();
    }

    private async Task OnHideModalClick()
    {
        await modal.HideAsync();
    }
}
```

I'll update the docs in the next release. It would be great if you could create a PR for this docs update.

**Comment by NhanNTWPV** [comment]
@gvreddy04 Apart from docs update, I'm more concerned about adherence to the original Bootstrap behaviour. Do you think we need actual code changes to ignore `CloseOnEscape` once `UseStaticBackdrop="true"`?

**Comment by NhanNTWPV** [comment]
#421 ready for your review, @gvreddy04
