### ISSUE TITLE
Bootsrap 5.3.2?

### ISSUE THREAD

**Issue by MarvinKlein1508** [vikramlearning/blazorbootstrap#418]
Is everything compatible with Bootstrap 5.3.2? 

The docs suggest to use 5.2.3.
https://demos.blazorbootstrap.com/getting-started/blazor-server

**Comment by LucaCris** [comment]
I'm currently on 5.3.0, in the middle... No problems. 😉

**Comment by MarvinKlein1508** [comment]
The only difference I've noticed by now is the change of the active color of the Accordion component.

**Comment by gvreddy04** [comment]
@MarvinKlein1508 I don't see any breaking changes. You can upgrade to 5.3.2.
