### ISSUE TITLE
Multiple Grid, Same Razor page

### ISSUE THREAD

**Issue by talanw** [vikramlearning/blazorbootstrap#437]
I'm currently working on an app with a couple of tabs. Each tab makes use of a grid however, if I choose to have a grid per tab it throws the following error:

grid requires data or dataprovider not both.

The grids are almost identical except different models use them as such:

                <Grid TItem="grid1data" Data="@grid1data" Class="table table-hover table-bordered table-striped" AllowPaging="true" PageSize="100" ItemsPerPageText="100" PageSizeSelectorItems="new int[] {20}" PaginationItemsTextFormat="">
                    <GridColumn TItem="grid1data" HeaderText="#">
                        @GetTeamRowNumber(context)
                    </GridColumn>
                    <GridColumn TItem="grid1data" HeaderText="heading1" PropertyName="heading1" SortKeySelector="item => item.heading1">
                        @context.heading1
                    </GridColumn>
                    <GridColumn TItem="grid1data" HeaderText="heading2" PropertyName="heading2" SortKeySelector="item => item.heading2">
                        @context.heading2
                    </GridColumn>
                </Grid>

The second grid is the same except that everything uses grid2data. I thought this would be allowed but throwing the error indicates otherwise. Can you advise?

**Comment by gvreddy04** [comment]
@talanw Thank you for using *BlazorBootstrap*. Please share the sample code or GitHUB repo with minimal steps to reproduce the issue. Also provide the below details:

.NET Version:
Blazor Web Assembly/Server:
BlazorBootstrap Version:
OS:
Browser:
