### ISSUE TITLE
Blazor Server - MainLayout.razor | ElementReference  => BlazorBootstrap.Sidebar error

### ISSUE THREAD

**Issue by schorges** [vikramlearning/blazorbootstrap#440]
NET 8.0 and  Blazor.Bootstrap 1.10.4 

Blazor Server - clear and add sample to MainLayout.razor 

the error:
` Fehler (aktiv)	CS0029	Der Typ "Microsoft.AspNetCore.Components.ElementReference" kann nicht implizit in "BlazorBootstrap.Sidebar" konvertiert werden`

**Comment by gvreddy04** [comment]
@schorges Will investigate this and update you back.

**Comment by MarvinKlein1508** [comment]
Hi @schorges 

Instead of 

```csharp
<Sidebar @ref="_sidebar" ....

@code {
private ElementReference _sidebar;
}
```

Use 
```csharp
<Sidebar @ref="_sidebar" ....

@code {
private Sidebar _sidebar;
}
```

Sidebar works perfectly fine for me in .NET 8.
