### ISSUE TITLE
.Net 8 Support

### ISSUE THREAD

**Issue by im-ashar** [vikramlearning/blazorbootstrap#444]
As we all know .net 8 has SSR so some components are not working like sidebar toggle and if i try to set rendermode on the sidebar it throws error that i cannot use render mode with this.

Is there any plan for .Net 8?

**Comment by gvreddy04** [comment]
@im-ashar we are working on the documentation for .NET 8.

**Comment by gvreddy04** [comment]
@im-ashar Please check #440 once.

**Comment by gvreddy04** [comment]
@im-ashar Pleae check the microsoft documentation for more info on the render modes. https://learn.microsoft.com/en-us/aspnet/core/blazor/components/render-modes?view=aspnetcore-8.0
