### ISSUE TITLE
Side Bar Menu Sub Menu for Blazor Web App .Net8

### ISSUE THREAD

**Issue by musully** [vikramlearning/blazorbootstrap#450]
Blazor Bootstrap Side bar is not working for Blazor Web App .Net8. Would you pls help us.

**Comment by gvreddy04** [comment]
@musully I'll share an example today.

**Comment by gvreddy04** [comment]
@musully Assuming that you are using Blazor Web App with Interactive Render Mode Server. Please confirm.

**Comment by musully** [comment]
> @musully Assuming that you are using Blazor Web App with Interactive Render Mode Server. Please confirm.

Blazor Web App .Net8, Authentication Type: Individual, Interactive Render Mode: Auto(Server And WebAssembly)

**Comment by gvreddy04** [comment]
@musully Thank you for trying **BlazorBootstrap**. Please ensure that you are using the Interactivity location as Global. There are some minor misconceptions regarding .NET Blazor SSR.

![image](https://github.com/vikramlearning/blazorbootstrap/assets/2337067/76307db1-35be-4a99-a81a-e2270538781c)

Please give it a try and let me know if you have any questions. I can provide more information if needed.

**Comment by musully** [comment]
Per page/component

**Comment by musully** [comment]
In this mode side menu is not working

![image](https://github.com/vikramlearning/blazorbootstrap/assets/50389286/b45ef608-3b64-4ebc-a4d0-d7a8b2997f50)

**Comment by MarvinKlein1508** [comment]
@musully you still need to apply a rendermode for the site/layout where the Sidebar is being used. 

The sidebar component needs interactivtity! Either setup your app to use global interactivity define a rendermode for the component itself.

For example:

```csharp
<Sidebar @rendermode="InteractiveServer" ...

```

**Comment by MarvinKlein1508** [comment]
You can read more about it here:
https://learn.microsoft.com/en-us/aspnet/core/blazor/components/render-modes?view=aspnetcore-8.0#apply-a-render-mode-to-a-component-definition

**Comment by gvreddy04** [comment]
@musully Please make the following highlighted changes to the **App.razor** page.

![image](https://github.com/vikramlearning/blazorbootstrap/assets/2337067/753bd183-954f-45a2-a3ff-443d262a45a2)
