### ISSUE TITLE
PreloadService.Hide has no effect (.NET8)

### ISSUE THREAD

**Issue by iron-dom** [vikramlearning/blazorbootstrap#454]
Preload is shown as expected but never dismissed or changed
PreloadService.Hide has no effect

Blazor 8 Project Server Sider Rendering, Component has StreamRendering(true)

Prelaod Component is added in MainLayout as 
``` razor
<div class="bb-page">
    <main>
        <article class="content px-4">
            <div class="py-2">
                @Body
            </div>
        </article>
    </main>
</div>

<Preload LoadingText="Bitte warten..." />
``` 
In the  razor page i do following
``` c#
 protected override async Task OnInitializedAsync()
 {
     PreloadService.Show(SpinnerColor.Light, "Loading data...");
     await Task.Delay(1000); // call the service/api
     PreloadService.Hide();
     PreloadService.Show(SpinnerColor.Danger, "Loading data 2...");
     await Task.Delay(2000); // call the service/api
     PreloadService.Hide();
}
``` 

 - BlazorBootstrap: [1.10.4]
 - Blazor Server
 - .NET Version: [ .NET 8]

 - OS: Windows 11
 - Browser Chrome
 - Version; 119.0

**Comment by gvreddy04** [comment]
@iron-dom Thank you for trying **BlazorBootstrap**. Please ensure that you are using the Interactivity location as Global. There are some minor misconceptions regarding .NET Blazor SSR.

![image](https://github.com/vikramlearning/blazorbootstrap/assets/2337067/76307db1-35be-4a99-a81a-e2270538781c)

Please give it a try and let me know if you have any questions. I can provide more information if needed.

**Comment by iron-dom** [comment]
Hi

Sorry didn’t have time to change it , I’ll get you feedback as soon as possible.


Thanks

Von: Vikram Gaddam ***@***.***>
Gesendet: Thursday, 7 December 2023 13:32
An: vikramlearning/blazorbootstrap ***@***.***>
Cc: Domagoj Mohl ***@***.***>; Mention ***@***.***>
Betreff: Re: [vikramlearning/blazorbootstrap] PreloadService.Hide has no effect (.NET8) (Issue #454)


@iron-dom<https://github.com/iron-dom> Any update?

**Comment by gvreddy04** [comment]
@iron-dom Please refer to the getting started guide for Blazor WebApp (.NET 8) - Interactive render mode Server - Global location here: https://docs.blazorbootstrap.com/getting-started/blazor-webapp-server-global-net-8.

Please create a new issue if you need further help.

**Comment by iron-dom** [comment]
Thanks! ! it works with as described, great project I love it . Merry Christmas

**Comment by iron-dom** [comment]
Thanks! ! it works as described, great project I love it . Merry Christmas

Thanks, Dom
Hi V
Von: Vikram Gaddam ***@***.***>
Gesendet: Wednesday, 20 December 2023 17:24
An: vikramlearning/blazorbootstrap ***@***.***>
Cc: Domagoj Mohl ***@***.***>; Mention ***@***.***>
Betreff: Re: [vikramlearning/blazorbootstrap] PreloadService.Hide has no effect (.NET8) (Issue #454)


@iron-dom<https://github.com/iron-dom> Please refer to the getting started guide for Blazor WebApp (.NET 8) - Interactive render mode Server - Global location here: https://docs.blazorbootstrap.com/getting-started/blazor-webapp-server-global-net-8.

Please create a new issue if you need further help.
