### ISSUE TITLE
Blazor Server NET 8.0, Microsoft.JSInterop.JSException if I navigate out a page with a Modal

### ISSUE THREAD

**Issue by antonioatom** [vikramlearning/blazorbootstrap#455]
**Describe the bug**
I'm new at blazor. Using the default Blazor App Server template with individual accounts. Following the getting started guide to add the blazor modal.

The modal works fine. I was able to add working modal. Everytime I navigate from a page that has the Modal component to another I get a JS error (see below). My pages are rendered as InteractiveServer

**To Reproduce**
1. Setup blazor bootstrap as explained in blazor bootstrap docs
2. Create a new page with @rendermode InteractiveServer
3. Add a simple modal
```
<button @onclick="RefreshAsync" class="btn btn-primary">Refresh</button>
<Modal @ref="modal" Title="Modal title" >
    <BodyTemplate>
        Modal body text goes here.
    </BodyTemplate>
    <FooterTemplate>
        <Button Color="ButtonColor.Secondary" @onclick="OnHideModalClick">Close</Button>
        <Button Color="ButtonColor.Primary">Save changes</Button>
    </FooterTemplate>
</Modal>

<Button Color="ButtonColor.Primary" @onclick="OnShowModalClick">Show Modal</Button>
@code {
    private Modal modal = default!;

    private async Task OnShowModalClick()
    {
        await modal.ShowAsync();
    }

    private async Task OnHideModalClick()
    {
        await modal.HideAsync();
    }
}

```
5. Open page and test the modal (or don't do anything)
6. Navigate to another page in the menu (default blazor template menu that uses `<NavLink class="nav-link" href="/AnotherPage">`

**Expected behavior**
No error should occur, I get 
```
Error: Microsoft.JSInterop.JSException: Cannot read properties of undefined (reading 'backdrop')
TypeError: Cannot read properties of undefined (reading 'backdrop')
    at On._initializeBackDrop (https://localhost:7189/lib/bootstrap/js/bootstrap.bundle.min.js:6:52555)
    at new On (https://localhost:7189/lib/bootstrap/js/bootstrap.bundle.min.js:6:51462)
    at On.getOrCreateInstance (https://localhost:7189/lib/bootstrap/js/bootstrap.bundle.min.js:6:7913)
    at Object.dispose (https://localhost:7189/_content/Blazor.Bootstrap/blazor.bootstrap.js:425:31)
    at https://localhost:7189/_framework/blazor.web.js:1:3244
    at new Promise (<anonymous>)
    at y.beginInvokeJSFromDotNet (https://localhost:7189/_framework/blazor.web.js:1:3201)
    at fn._invokeClientMethod (https://localhost:7189/_framework/blazor.web.js:1:62541)
    at fn._processIncomingData (https://localhost:7189/_framework/blazor.web.js:1:60016)
    at connection.onreceive (https://localhost:7189/_framework/blazor.web.js:1:53657)
   at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, Object[] args)
   at Microsoft.JSInterop.JSRuntimeExtensions.InvokeVoidAsync(IJSRuntime jsRuntime, String identifier, Object[] args)
   at BlazorBootstrap.Modal.DisposeAsync(Boolean disposing)
   at BlazorBootstrap.BlazorBootstrapComponentBase.DisposeAsync()
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.<ProcessDisposalQueueInExistingBatch>g__GetHandledAsynchronousDisposalErrorsTask|79_0(Task result)
log @ blazor.web.js:1
unhandledError @ blazor.web.js:1
(anonymous) @ blazor.web.js:1
_invokeClientMethod @ blazor.web.js:1
_processIncomingData @ blazor.web.js:1
connection.onreceive @ blazor.web.js:1
i.onmessage @ blazor.web.js:1

Information: Connection disconnected.
```

**Versions (please complete the following information):**
 - BlazorBootstrap: 1.10.4
 - Blazor WebAssembly / Server: .NET 8.0 version
 - .NET Version: .NET 8.0

EDIT: Like I said, I'm new at blazor so I might be missing something or adding something wrong. If that's the case can you please explain what might be the issue?

**Comment by gvreddy04** [comment]
@antonioatom Thank you for trying **BlazorBootstrap**. Please ensure that you are using the Interactivity location as Global. There are some minor misconceptions regarding .NET Blazor SSR.

![image](https://github.com/vikramlearning/blazorbootstrap/assets/2337067/76307db1-35be-4a99-a81a-e2270538781c)

Please give it a try and let me know if you have any questions. I can provide more information if needed.

**Comment by antonioatom** [comment]
@gvreddy04 Thanks for your reply. Created an empty project with those settings and it seems to work.
I think the problem was also in my case I was also using Interactive Auto which made a bigger mess of of things in my head.

One note though, when using the default pages for the "Individual" authentication type, if I add a modal to any of those pages it won't work. Not that this is terrible important, just noticed that on my tests.

I think this is because of the render mode applied to those pages

```
    private IComponentRenderMode? RenderModeForPage => HttpContext.Request.Path.StartsWithSegments("/Account")
        ? null
        : InteractiveServer;
```

I also created the same project using Interactive Auto and added a modal to the Weather sample page and this also seems to work. Since interactive auto adds 2 projects I've added the blazor registration on both I think for future .net 8 docs this could be mentioned (in which project you need to put what). Also the mention that all /Account pages might not work with some components is something new people might not know, I guess.

Anyway, all good now as long as I stick with using Global as the interactivity location.

Again thanks so much for you quick reply.

**Comment by gvreddy04** [comment]
@antonioatom We are working on the .NET 8 setup docs. It is a work in progress. In a few days, we will add that.
