### ISSUE TITLE
Grid: Filters - Enum support

### ISSUE THREAD

**Issue by wumingcp-ps** [vikramlearning/blazorbootstrap#485]
When I use BlazorBootstrap to create the Grid componment, I want to show some enum in the Grid, and filter them, but the filter button is disabled, when I check the code and find there is no EnumFilterOperator, do you have plan to add one? thanks

[blazorbootstrap/Components/Grid/FilterOperatorHelper.cs](https://github.com/vikramlearning/blazorbootstrap/blob/14c703fb4885bae510aeb62153e6a35a0234853f/blazorbootstrap/Components/Grid/FilterOperatorHelper.cs#L3)

**Comment by gvreddy04** [comment]
@wumingcp-ps Thank you for reaching out to us. We will be happy to add these two enhancements.

To ensure clarity and maintainability, could you please create a separate issue for the "String NotEqual" filter? This will allow us to track and address each enhancement independently.

**Comment by wumingcp-ps** [comment]
> @wumingcp-ps Thank you for reaching out to us. We will be happy to add these two enhancements.
> 
> To ensure clarity and maintainability, could you please create a separate issue for the "String NotEqual" filter? This will allow us to track and address each enhancement independently.

Sure, create another issue: https://github.com/vikramlearning/blazorbootstrap/issues/486

**Comment by Sicarii-Dev** [comment]
Bump, this functionality would be greatly appreciated or an alternative would be the option to specify a func with string return type so that the existing filters could be used.
