### ISSUE TITLE
Korean text entered twice or printed strangely

### ISSUE THREAD

**Issue by nanenchanga53** [vikramlearning/blazorbootstrap#505]
**Describe the bug**
Korean text entered twice or printed strangely

**To Reproduce**
1. Insert Korean Text 김우창 for Input Control
2. I want to write "김우창" in Korean, but I can't

**Expected behavior**

**Screenshots**
![image](https://github.com/vikramlearning/blazorbootstrap/assets/39551265/a4dd2af1-2041-4839-b246-7c1772e473e7)
![image](https://github.com/vikramlearning/blazorbootstrap/assets/39551265/2698c79f-51c9-4943-a309-1cd2128260d7)

**Versions (please complete the following information):**
 - BlazorBootstrap: 1.10.4
 - Blazor WebAssembly / Server: [e.g. WebAssembly, Server]
 - .NET Version: NET 8

**Sample code**
Sample code to reproduce the issue.

<div class="row">
    <div class="col-md-5 col-sm-12">
        <AutoComplete @bind-Value="customerName"
                      TItem="Customer"
                      DataProvider="CustomersDataProvider"
                      PropertyName="CustomerName"
                      Placeholder="Search a customer..."
                      StringComparison="StringComparison.Ordinal"
                      OnChanged="(Customer customer) => OnAutoCompleteChanged(customer)" />
    </div>
</div>

@code {
    private string customerName;

    public IEnumerable<Customer> customers;

    private async Task<AutoCompleteDataProviderResult<Customer>> CustomersDataProvider(AutoCompleteDataProviderRequest<Customer> request)
    {
        if (customers is null) // pull customers only one time for client-side autocomplete
            customers = GetCustomers(); // call a service or an API to pull the customers

        return await Task.FromResult(request.ApplyTo(customers.OrderBy(customer => customer.CustomerName)));
    }

    private IEnumerable<Customer> GetCustomers()
    {
        return new List<Customer> {
            new(1, "Pich S"),
            new(2, "sfh Sobi"),
            new(3, "Jojo chan"),
            new(4, "Jee ja"),
            new(5, "Rose Canon"),
            new(6, "Manju A"),
            new(7, "Bandita PA"),
            new(8, "Sagar Adil"),
            new(9, "Isha Wang"),
            new(10, "Daina JJ"),
            new(11, "Komala Mug"),
            new(12, "Dikshita BD"),
            new(13, "Neha Gosar"),
            new(14, "Preeti S"),
            new(15, "Sagar Seth"),
            new(16, "Vinayak MM"),
            new(17, "Vijaya Lakhsmi"),
            new(18, "Jahan K"),
            new(19, "Joy B"),
            new(20, "Zaraiah C"),
            new(21, "Laura L"),
            new(22, "Punith ES")
        };
    }

    private void OnAutoCompleteChanged(Customer customer)
    {
        // TODO: handle your own logic

        // NOTE: do null check
        Console.WriteLine($"'{customer?.CustomerName}' selected.");
    }
}

**GitHub repo**
GitHub repo with minimal code to reproduce the issue.

**Desktop (please complete the following information):**
 - OS: Window
 - Browser chrome, Edge
 - Version 

**Additional context**

Is it possible to change the input control by overriding it?
If you just input, you can write something else, but I want to change Grid's filtering.

**Comment by MarvinKlein1508** [comment]
It works fine for me when I have the item in my list.
```csharp
    private IEnumerable<Customer> GetCustomers()
    {
        return new List<Customer> {
            new(1, "김우창"),
            new(2, "sfh Sobi"),
            new(3, "Jojo chan"),
            new(4, "Jee ja"),
            new(5, "Rose Canon"),
            new(6, "Manju A"),
            new(7, "Bandita PA"),
            new(8, "Sagar Adil"),
            new(9, "Isha Wang"),
            new(10, "Daina JJ"),
            new(11, "Komala Mug"),
            new(12, "Dikshita BD"),
            new(13, "Neha Gosar"),
            new(14, "Preeti S"),
            new(15, "Sagar Seth"),
            new(16, "Vinayak MM"),
            new(17, "Vijaya Lakhsmi"),
            new(18, "Jahan K"),
            new(19, "Joy B"),
            new(20, "Zaraiah C"),
            new(21, "Laura L"),
            new(22, "Punith ES")
        };
    }
```
![grafik](https://github.com/vikramlearning/blazorbootstrap/assets/32510006/a1489a91-7fdb-4ab8-bba1-9fe8ffbda4f3)

**Comment by nanenchanga53** [comment]
No, there's a problem when typing.

**Comment by gvreddy04** [comment]
@nanenchanga53 Can you share a screen recording to help me understand better?

**Comment by gvreddy04** [comment]
@nanenchanga53 If you are facing this issue, please create a separate issue and share a GitHub repository with minimal steps to reproduce the problem. Additionally, sharing a screen recording would be helpful for understanding the issue better.

If there are any setup steps for my keyboard language, please share them. I'm not familiar with Korean.

**Comment by nanenchanga53** [comment]
fast english typing has same issue

https://github.com/vikramlearning/blazorbootstrap/assets/39551265/a84474fc-d6a3-479c-bf5c-fa189097cc20
