### ISSUE TITLE
TreeList Grid & EditMode.Grid = Inline & Custom-Select - CheckBox

### ISSUE THREAD

**Issue by mrcorale** [vikramlearning/blazorbootstrap#514]
1.Will the Edit Mode.Grid option be set to Inline? 
2. Adding Custom-Select functionality via CheckBox of list items?
3.TreeList Grid in Blazor Server in the near future will be implemented or not?
4.In modal or in form - fields such as DateTime and Numeric will it be possible to apply LocalRegion?
Thanks for the reply.

**Comment by gvreddy04** [comment]
> DateTime and Numeric will it be possible to apply LocalRegion

Pls use CurrencyInput without symbol.

Refer:

- https://docs.blazorbootstrap.com/forms/currency-input#show-currency-symbols-for-the-different-locales
- https://docs.blazorbootstrap.com/forms/currency-input#hide-currency-symbol

**Comment by gvreddy04** [comment]
> Will the Edit Mode.Grid option be set to Inline?

Not planned at this moment.

**Comment by gvreddy04** [comment]
> 2. Adding Custom-Select functionality via CheckBox of list items?
> 3.TreeList Grid in Blazor Server in the near future will be implemented or not?

@mrcorale Please create seperate issues for these, will add in the future releases.
