### ISSUE TITLE
Modal does not obey data-bs-theme

### ISSUE THREAD

**Issue by daveclarkit** [vikramlearning/blazorbootstrap#522]
when opening a Modal the header is drawn in light mode even if you have data-bs-theme="dark" set

**To Reproduce**
1. Create a new project using Bootstrap Blazor
2. Set data-bs-theme="dark"
3. Create a Modal
4. Open Modal
5. See error

**Expected behavior**
Should be Dark!.

![image](https://github.com/vikramlearning/blazorbootstrap/assets/113099875/ecb898bf-56e7-464a-92b0-2a5cfaf476fe)

**Versions (please complete the following information):**
 - BlazorBootstrap: 1.10.5
 - Blazor WebAssembly 
 - .NET Version: 8

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: edge
 - Version 122.0.2348.0 (Official build) stable app, dev channel (64-bit)

**Comment by MarvinKlein1508** [comment]
Can confirm this. 

As a workaround you can set `ModalType="ModalType.Dark"`

**Comment by MarvinKlein1508** [comment]
@gvreddy04 I took another look on this and added a PR to fix this.
