### ISSUE TITLE
Update docs to Bootstrap 5.3.2 and Bootstrap Icons 1.11.3

### ISSUE THREAD

**Issue by MarvinKlein1508** [vikramlearning/blazorbootstrap#523]
Your docs in the getting started guide suggests to import Bootstrap 5.2.3 and Bootstrap Icons 1.10.3. This should be Updated to Bootstrap 5.3.2 and Bootstrap Icons 1.11.3.

https://docs.blazorbootstrap.com/getting-started/blazor-webassembly-net-8
https://docs.blazorbootstrap.com/getting-started/blazor-webapp-server-global-net-8
https://docs.blazorbootstrap.com/getting-started/blazor-webapp-auto-global-net-8
https://docs.blazorbootstrap.com/getting-started/maui-blazor-net-8
https://docs.blazorbootstrap.com/getting-started/blazor-webassembly-net-7
https://docs.blazorbootstrap.com/getting-started/blazor-server-net-7
https://docs.blazorbootstrap.com/getting-started/maui-blazor-net-7
https://docs.blazorbootstrap.com/getting-started/blazor-webassembly-net-6
https://docs.blazorbootstrap.com/getting-started/blazor-server-net-6

Especially the Bootstrap Icons link because you are already supporting these icons.

**Comment by gvreddy04** [comment]
@MarvinKlein1508 I'll check and update. Thanks for reporting.
