### ISSUE TITLE
Grid: Is there a way to programmatically unselect all rows in a grid with multi-select mode

### ISSUE THREAD

**Issue by roysurles** [vikramlearning/blazorbootstrap#536]
**Describe the bug**
Cannot find a programmatic method to unselect all rows in a grid with multi-select mode

**Expected behavior**
Add programmatic method to unselect all rows in a grid with multi-select mode

.Net Blazor Server
Blazor.Bootstrap Version=1.10.5

**Comment by gvreddy04** [comment]
@roysurles Thanks for choosing BlazorBootstrap! We haven't yet made a public method available for this functionality, but we'd love to learn more about your use case. Providing additional context about your scenario will help us understand your needs and plan an enhancement accordingly.
