### ISSUE TITLE
Is there a way to have fixed headers in the grid, and set a max-height, and scroll vertically if there are more rows than the max-height?

### ISSUE THREAD

**Issue by roysurles** [vikramlearning/blazorbootstrap#537]
.Net 8
Blazor Server
Blazor.Bootstrap Version=1.10.5

**Comment by gvreddy04** [comment]
@roysurles Thank you for using BlazorBootstrap. Please take look at https://docs.blazorbootstrap.com/components/grid#fixed-header.

**Comment by gvreddy04** [comment]
demos: https://demos.blazorbootstrap.com/grid
