### ISSUE TITLE
Please provide Dark mode support

### ISSUE THREAD

**Issue by koyiit** [vikramlearning/blazorbootstrap#564]
Please add dark mode support.

https://getbootstrap.com/docs/5.3/customize/color-modes/#dark-mode

**Comment by gvreddy04** [comment]
@koyiit Thank you for trying BlazorBootstrap. We will support this new feature in the upcoming releases.

**Comment by talanw** [comment]
Any update on which release this will be coming in? I'd like to get this added to my project for individuals who struggle without it.

**Comment by gvreddy04** [comment]
@talanw We might add in the next release (2.2.0) or 2.3.0.

**Comment by talanw** [comment]
@gvreddy04 did you manage to get a dark mode release available for version 3? I can’t see it in any of the changes so thought I’d ask.

**Comment by talanw** [comment]
@gvreddy04 I see you've got DarkMode support now in 3.1.0. This is awesome, thank you so much. Looking forward to getting this installed on our system. I'll take a look at the user guides for installing this shortly.

**Comment by talanw** [comment]
HI @gvreddy04 I've taken a look at the documentation site and there isn't any configuration example for setting up the different themes. I've been taking a look at the code and can see that you've assigned the dropdown to each of the demos. It would be good if you could provide a brief description of the process to enable this for your library. Thanks

**Comment by gvreddy04** [comment]
@talanw I'm creating a ThemeSwitcher component. It is a work in progress (WIP) at this moment. It will be available in version 3.2.0. For now, you can try the WIP feature by calling `<ThemeSwitcher />`.

**Comment by talanw** [comment]
@gvreddy04 Yep that's pulled through the dropdown which is great. I need to do a bit of CSS work to move the dropdown to the correct position. Setting the theme doesn't change it at the moment. I'm guessing that's because it's a work in progress so once 3.2.0 becomes available I'm hopeful that everything should be good.
