### ISSUE TITLE
Sidebar 2 Component

### ISSUE THREAD

**Issue by gvreddy579** [vikramlearning/blazorbootstrap#565]
### Discussed in https://github.com/vikramlearning/blazorbootstrap/discussions/561

<div type='discussions-op-text'>

<sup>Originally posted by **doxuyenxo** February 15, 2024</sup>
Hi Bros,

I'm trying to build the sidebar as recursive, the BlazorBootstrap only support 2 levels for now.
Could you support recursive or anyway to custom current sidebar as recursive please?</div>

**Comment by gvreddy04** [comment]
@MarvinKlein1508 We will add this feature in the next release.
