### ISSUE TITLE
Comment on #563

### ISSUE THREAD

**Issue by stsrki** [vikramlearning/blazorbootstrap#572]
Comment on #563

I believe I was not rude at all; in fact, I was only stating the facts without commenting on anything that might come as offensive. If anything, I should have been less restraining myself. But, no worries. Your own response and your own way of not going with how the community works and not addressing the problem at all is saying enough about you. And to top it all, you have locked this conversation to everyone, which is fully backing up my claim. 

Best

**Comment by gvreddy579** [comment]
Taken care of adding credits in https://github.com/vikramlearning/blazorbootstrap/pull/576
