### ISSUE TITLE
PdfViewer Issue on live Preview

### ISSUE THREAD

**Issue by AliAsghar42** [vikramlearning/blazorbootstrap#609]
It is Perfectly working in local System.
But when I publish app on live

Error:crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: Failed to fetch dynamically imported module: `https://**********.com/BLERGQ78ACK10/_content/Blazor.Bootstrap/blazor.bootstrap.pdf.js`
      TypeError: Failed to fetch dynamically imported module: `https://**********.com/BLERGQ78ACK10/_content/Blazor.Bootstrap/blazor.bootstrap.pdf.js`
Microsoft.JSInterop.JSException: Failed to fetch dynamically imported module: `https://**********.com/BLERGQ78ACK10/_content/Blazor.Bootstrap/blazor.bootstrap.pdf.js`
TypeError: Failed to fetch dynamically imported module: `https://**********.com/BLERGQ78ACK10/_content/Blazor.Bootstrap/blazor.bootstrap.pdf.js`
   at Microsoft.JSInterop.JSRuntime.<InvokeAsync>d__16`1[[Microsoft.JSInterop.IJSObjectReference, Microsoft.JSInterop, Version=6.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]].MoveNext()
   at BlazorBootstrap.PdfViewerJsInterop.GotoPageAsync(Object objRef, String elementId, Int32 gotoPageNum)
   at BlazorBootstrap.PdfViewer.PageNumberChangedAsync(Int32 value)
   at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)

**Comment by gvreddy04** [comment]
@AliAsghar42 Thank you for trying **BlazorBootstrap**. I have updated the URLs in the error message to ensure your server information is not disclosed.

One suggestion: Please make sure you are not posting any sensitive information.

Can you provide the following information?

.NET Version:
Blazor (Server/WebAssembly):
Blazor Render Mode (Global or Per Page/Component):
Browser:
OS:
Build Pipeline (Azure/GitHub/Manual):
Deployed Environment (Windows Server/Azure Cloud):

Please also provide a GitHub repository with minimal code to reproduce the issue.

**Comment by AliAsghar42** [comment]
@gvreddy04 Thank You So much For Updating URLs.

.NET Version:  **4.8**
**Blazor WebAssembly**
**Global Render Mode**
Browser: **Chrome**
OS: **Windows Server**

I can't Provide Git Hub Repository Beacuse I dont even have a access to invite

check this:
    <PdfViewer Class="mb-3 h-100 w-100 pdf-viewer" Url="@nPdfBase64" />

@nPdfBase64 contains Base64ofPDF
nPdfBase64 = "data:application/pdf;base64," + nPdfBase64;

Working Perfectly in Local System
Kindly Provide a Solution ASAP

**Comment by AliAsghar42** [comment]
[Sample Code.txt](https://github.com/vikramlearning/blazorbootstrap/files/14562190/Sample.Code.txt)

**Comment by AliAsghar42** [comment]
[Sample Code 2.txt](https://github.com/vikramlearning/blazorbootstrap/files/14562279/Sample.Code.2.txt)

I create a dummy Project and Publish it

Still same issue

**Comment by AliAsghar42** [comment]
check here Live Url:
https://www.genteccrm.com/BLERGQ78ACK10/pdf

**Comment by gvreddy04** [comment]
@AliAsghar42 The page may not be loading due to a checksum issue. Would you like to try redeploying?

![image](https://github.com/vikramlearning/blazorbootstrap/assets/2337067/28a95ff9-70ae-490b-97c6-9003b4730e00)

**Comment by gvreddy04** [comment]
@AliAsghar42 There will most likely be an issue with your deployment only. How are you deploying to the server?

**Comment by AliAsghar42** [comment]
@gvreddy04  But all the other things are working perfectly.
I create publish in a folder and then deploy it on IIS Server

**Comment by gvreddy04** [comment]
@AliAsghar42 Were you able to view the PDF at https://demos.blazorbootstrap.com/pdf-viewer? These are Blazor WebAssembly demos.

**Comment by aasghar110** [comment]
Perfectly viewing here
https://demos.blazorbootstrap.com/pdf-viewer

@gvreddy04 can you please share me the Blazor WebAssembly project with PDFViewer?
I tried so many times by creating new projects.
Still same issue in PDFViewer. But other components works perfectly.

**Comment by AliAsghar42** [comment]
@gvreddy04 Kindly Provide a Solution.

**Comment by AliAsghar42** [comment]
@gvreddy04 
I found a issue in my IIS Server 
MIME type .mjs file issue

ThankYou.

**Comment by AliAsghar42** [comment]
@gvreddy04 Any plans to add Download & print Option?

**Comment by gvreddy04** [comment]
@AliAsghar42 Will handle in [PDF Viewer: Download and Select Text #549](https://github.com/vikramlearning/blazorbootstrap/issues/549). 

For Pdf print please create a seperate story.
