### ISSUE TITLE
.Net8 or 6?

### ISSUE THREAD

**Issue by gpcottle** [vikramlearning/blazorbootstrap#610]
Hi
I have attempted to install Blazor.Bootstrap on my .Net8 application and it has asked to install .Net6 into my application. Is there a way to use the library without installing .Net6? 
Thanks

**Comment by gvreddy04** [comment]
@gpcottle Could you please share the screenshot?

**Comment by gpcottle** [comment]
Hi @gvreddy04 
Screenshot as below:
![image](https://github.com/vikramlearning/blazorbootstrap/assets/19620782/44767375-2748-40d2-9dcd-53663a15e9e9)

**Comment by gvreddy04** [comment]
@gpcottle Please install .NET 6 on your machine.

**Comment by gvreddy04** [comment]
@gpcottle Please check the starter project for quick reference.

Link: https://github.com/vikramlearning/blazorbootstrap-starter-templates/tree/master/src/BlazorBootstrap.Templates.Starter/NET8.BlazorWebAppRenderModeServerGlobal

**Comment by gpcottle** [comment]
OK - not the solution I was looking for. I'll hold off on the library until the dependency is changed
