### ISSUE TITLE
BarChart Width & Height properties translate to wrong style

### ISSUE THREAD

**Issue by bheinrich17** [vikramlearning/blazorbootstrap#613]
Following html:
![grafik](https://github.com/vikramlearning/blazorbootstrap/assets/155624215/161b623e-ec38-4452-9281-241751d6cfa3)

Leads to:
![grafik](https://github.com/vikramlearning/blazorbootstrap/assets/155624215/8668a3b7-d81c-4836-bafd-7cc6696bb33a)

Width and height style arn't properly separarted by ";".

**Comment by gvreddy04** [comment]
@bheinrich17 Thank you for reporting this issue.
