### ISSUE TITLE
Button attribute stopPropagation

### ISSUE THREAD

**Issue by bluezeus** [vikramlearning/blazorbootstrap#615]
The button does not support the attributes @onclick:stopPropagation="true" and @onclick:preventDefault="true".

**Comment by gvreddy04** [comment]
@bluezeus Thank you for using BlazorBootstrtap. Please check the below link.

https://learn.microsoft.com/en-us/aspnet/core/blazor/components/event-handling?view=aspnetcore-8.0#stop-event-propagation
