### ISSUE TITLE
Dynamically created tabs cannot be removed

### ISSUE THREAD

**Issue by odskee** [vikramlearning/blazorbootstrap#627]
**Describe the bug**
After rendering a \<Tab\> dynamically using a foreach loop, the tab will remain displayed after being removed from the dynamic source.

**To Reproduce** / **Sample code**
```
<Tabs ref="@pTabs" NavStyle="NavStyle.VerticalUnderline" Class=".nav-fill">
    @foreach(MyProfileModel _profile in Profiles)
    {
        <Tab Title="@_profile.Name" IsActive="@_profile.IsDefault" OnClick="(a => ProfileTabClicked(_profile.Id))">
            <Content><h1>Profile @_profile.Name</h1></Content>
        </Tab>
    }
</Tabs>

@code{
    [Parameter] public List<MyProfileModel> Profiles {get; set;]
    Tabs pTabs = default!;
    MyProfileModel SelectedProfile  = default!;
    ...

    void RemoveTab(MyProfileModel Profile){
        Profiles.Remove(Profile);
        StateHasChanged();
    }
}
```

In this case, after calling RemoveTab, no UI changes are applied and the tab created from the removed object is still displayed.  The tab can still be selected and bound input elements still update a bound object despite the object no longer existing.

**Expected behavior**
After removing an object from the List\<T\> source, the \<Tabs\> component should be re-rendered, no longer showing a \<Tab\> for the removed objects.

**Versions (please complete the following information):**
 - BlazorBootstrap: 2.1.0
 - Blazor WebAssembly / Server: Blazor / MAUI Hybrid
 - .NET Version: .NET 8

**Additional context**

**Comment by gvreddy04** [comment]
@odskee Thank you for using **BlazorBootsrap**. Support for this feature will be added in the next version. Currently, removing tabs is not supported.
