### ISSUE TITLE
Grid pagination with external component

### ISSUE THREAD

**Issue by agriffard** [vikramlearning/blazorbootstrap#637]
Could you please explain how to use an external component to control the pagination of a grid?

The Grid does not seem to expose properties to retrieve the current pageSize, pageNumber, ...

I tried to use the Pagination component but when I change the ActivePageNumber programmatically after a PageChanged event, it does not seem to be updated.

**Comment by gvreddy04** [comment]
@agriffard Sorry for the late response and thank you for trying **BlazorBootstrap**. At this moment, external pagination is not supported. However, you can try using **GridSettingsProvider**.

Link: https://docs.blazorbootstrap.com/components/grid#save-and-load-grid-settings
