### ISSUE TITLE
Date Sequence in Line Charts 

### ISSUE THREAD

**Issue by PraveeshKS** [vikramlearning/blazorbootstrap#643]
Hey there , 
I would like to know whether we can create a date sequence in the X axis of a line chart , for example if I have only two dates which will be start date and end date , is it possible to generate the dates in between in this period automatically in the X axis to plot the data ?

**Comment by gvreddy04** [comment]
@PraveeshKS It is possible. To get started, prepare some data like the example below.

Link: https://demos.blazorbootstrap.com/charts#blazor-charts-example

In the screenshot below, we are displaying data for 20 overs.

![image](https://github.com/vikramlearning/blazorbootstrap/assets/2337067/0ec01541-4484-49c6-a25e-2ca5dd64737b)

![image](https://github.com/vikramlearning/blazorbootstrap/assets/2337067/e7b2b7c2-00ee-4fc5-a4df-077bd15bbf11)
