### ISSUE TITLE
Darkmode

### ISSUE THREAD

**Issue by maxdnet** [vikramlearning/blazorbootstrap#651]
### Discussed in https://github.com/vikramlearning/blazorbootstrap/discussions/466

<div type='discussions-op-text'>

<sup>Originally posted by **ecospecifier** December 12, 2023</sup>
With bootstrap 5.3 will we see Blazor Bootstrap embrace darkmode firstclass? I notce a lot of components like eg. toasts don't respect the darkmode class on the body of the parent.</div>

**Comment by sikora507** [comment]
There is even a dark/light mode switch on blazorBootstrap docs site https://docs.blazorbootstrap.com/
Before the feature is implemented, can we know how this was done? It looks similar to how bootstrap 5.3 handles darkmode but the attribute name is slightly different:
![image](https://github.com/vikramlearning/blazorbootstrap/assets/4272052/a4154aaa-3fdd-428f-8fee-2d171f9ed39b)
How this is done with Blazor? When I tried using my webassemply component to write to localstorage and use immediately invoked function expression to set the proper theme on page render, it works when I refresh the page, but when I navigate through links, the attribute keeps disappearing.

**Comment by Lucasharskamp** [comment]
I agree that this is a sorely needed feature, plus the necessary documentation to get it easily up and running in our projects.

**Comment by devtrix** [comment]
Any update on this?

**Comment by gvreddy04** [comment]
We are working on this. Please check #707 for more updates.
