### ISSUE TITLE
Grid Filter Button CSS

### ISSUE THREAD

**Issue by thatplatypus** [vikramlearning/blazorbootstrap#688]
Hello,

First of all, I appreciate your work on this library, it's quickly become my favorite go-to.

Is there a way to add additional classes to the grid's filter column button? The light color doesn't look so good on my theme. There's definitely other workarounds I can explore but wanted to check first.

If that's not possible, but seems valuable, and also not a priority, I could try and throw a PR together for it at some point, I imagine it'd be as simple as exposing a property through `Grid`, `GridColumn`, or `GridColumnFilter`?

Either way,
Thanks

**Comment by gvreddy04** [comment]
@thatplatypus Thank you for using BlazorBootstrap. Can you share a sample screenshot of your theme and the filter button's color? This is only for our better understanding. Please mask any sensitive information in the screenshot.

**Comment by gvreddy04** [comment]
@thatplatypus We are planning to release this enhancement in the next release.
