### ISSUE TITLE
Remove the internal modifier for BlazorBootstrapComponentBase to allow creating custom components using this wonderful core

### ISSUE THREAD

**Issue by yeifer-co** [vikramlearning/blazorbootstrap#690]
**Describe the bug**
I'm attempting to create my own components based on the core of the BlazorBootstrap library, but I don't have access to some properties of the BlazorBootstrapComponentBase class because they are marked as internal. I would like to use this core as I find it very well-made. I want to define my own components for scenarios not covered by the available components in the library. In case it's not possible to remove the internal modifier due to reasons beyond my understanding, please provide a method for creating new components based on this core.

**To Reproduce**
1. Attempt to create a custom component extending BlazorBootstrapComponentBase.
2. Notice the inability to access certain properties or methods due to their internal modifier.
3. Encounter limitations in creating custom components based on the BlazorBootstrap library's core functionality.

**Expected behavior**
I expect to be able to access all necessary properties and methods of the BlazorBootstrapComponentBase class to create custom components seamlessly.

**Sample code**
Sample code to reproduce the issue.
```razor
@namespace BlazorBootstrap
@inherits BlazorBootstrapComponentBase

<MyCustomComponent implementation>
````

````razor.cs
namespace BlazorBootstrap;

public partial class MyCustomComponent : BlazorBootstrapComponentBase
{
     protected override void BuildClasses() {
            // Cannot access to AddClass because it is internal
     }
}
````

**Comment by mrpmorris** [comment]
@yeifer-co You should think carefully if you will be breaking copyright law by copying any code in this repo.

https://twitter.com/MrPeterLMorris/status/1786750236137857371

**Comment by gvreddy04** [comment]
@yeifer-co After next version, please use the below approach.

**Example:** 
```cs
protected override string? ClassNames =>
    new CssClassBuilder(Class)
        .AddClass(BootstrapClass.Accordion)
        .AddClass(BootstrapClass.AccordionFlush, Flush)
        .Build();
```
