### ISSUE TITLE
[Documentation] Wrong package version in Getting Started guide for Blazor for .Net8 Auto

### ISSUE THREAD

**Issue by purquiz** [vikramlearning/blazorbootstrap#696]
**Describe the bug**
The Getting Started documentation for Blazor on Net8, auto rendering, is mentioning an old version of the Blazor.Bootstrap nuget package within the Install section for the Client application.

It says "Install-Package Blazor.Bootstrap -Version 1.10.4"
It should say "Install-Package Blazor.Bootstrap -Version 2.2.1"

**To Reproduce**
1. Navigate to https://docs.blazorbootstrap.com/getting-started/blazor-webapp-auto-global-net-8
2. Scroll to the Client section
3. See the wrong version in the Install-Package command.

**Expected behavior**
The Nuget package version should be the latest.

**Comment by gvreddy04** [comment]
@purquiz Thank you for reporting this. It would be great if you could create a PR for this document.

**Comment by purquiz** [comment]
@gvreddy04 sure, I will do as soon as I get home tonight.
