### ISSUE TITLE
Copyright infringement

### ISSUE THREAD

**Issue by mrpmorris** [vikramlearning/blazorbootstrap#710]
You are doing massive harm to both your professional and personal reputations.

People simply aren't going to see you as trustworthy, especially those who may need to give you access to confidential materials. 

The evidence is ironclad. Even if you rewrite everything from scratch, you've still demonstrated traits of untrustworthiness and deception, broken multiple international laws, and violated terms and conditions of both GitHub and Nuget.

https://twitter.com/MrPeterLMorris/status/1786750236137857371

I recommend removing your repo and nuget packages before your reputation is damaged to the point you become unemployable.

**Comment by gvreddy04** [comment]
@mrpmorris Hope you remember issue [Date Picker Component #142](https://github.com/vikramlearning/blazorbootstrap/issues/142).

You praised our work and requested for DatePicker component. Just check, how those components implemented before raising all these.

If you are a fan of Blazorise, please go and use it.

Is Blazorise scared of BlazorBootstrap growth? BlazorBootstrap will be free and open source.

Every BlazorBootstrap component works as native as Bootstrap. Our implementation is native to Bootstrap.

I don't know why you are creating unnecessary drama here by comparing old code, creating GitHub issues to defame BlazorBootstrap. Just check all the components how those are actually implemented not the Enum name matching, etc. Please check the latest repo. There is no need to learn rocket science to write a Blazor component library.

Please educate us on the relevant international laws and section numbers with references.

If they have any issues, they will come to us, why you are worried, I don't understand.

Hope you know what's going on between us and Blazorise. If not, educate yourself.

**Comment by mrpmorris** [comment]
I did praise the work, I just didn't realise at the time you were stealing it from someone else.

If you steal someone else's work and they don't like it, that doesn't make them scared, it just makes you unethnical. I'm not creating drama, I am making you aware of the damage you are doing.

The law is called "copyright".

**Comment by stsrki** [comment]
I will leave this here for future reference. The following screenshots are part of Blazorise SLA starting from June 2021, two months before blazorbootstrap contained the first copy of Blazorise files and source code:

![image](https://github.com/vikramlearning/blazorbootstrap/assets/900302/dc4bfb7f-e425-456c-ba32-6845f5908d7e)

![image](https://github.com/vikramlearning/blazorbootstrap/assets/900302/9cf96c98-1e0c-4654-aad3-83287d164c1f)

![image](https://github.com/vikramlearning/blazorbootstrap/assets/900302/9c94d528-351d-4c55-9d27-e56015633c71)

Which clearly states that you broke Blazorise T&C. Aside from the part that you copied Blazorise code. You also modified it to a large extent and redistributed it to third parties.

**Comment by gvreddy04** [comment]
@stsrki @mrpmorris 

We informed the BlazorBootstrap community that if they are using an older version for commercial purposes, they should reach out to the Blazorise team for licensing.

https://docs.blazorbootstrap.com/blog/2024/02/25/upgrade-to-v2.0.0

![image](https://github.com/vikramlearning/blazorbootstrap/assets/2337067/72a1cb5b-a890-41a2-ae58-30011ee8837f)

**Comment by mrpmorris** [comment]
Your latest source is still a copy, they'll still be breaking the law. 

And telling them also doesn't change the fact that you broke the law when you did it, and are continuing to do so. 

But I am not here to teach you the law. I recommend you seek advice from a legal expert in copyright law before deciding what to do next.
