### ISSUE TITLE
Modal close "X" button with bootstrap 5.3.3

### ISSUE THREAD

**Issue by XenoWizard** [vikramlearning/blazorbootstrap#714]
![image](https://github.com/vikramlearning/blazorbootstrap/assets/40558424/2b10b913-8293-412c-b838-43e02ba1c8c2)

**To Reproduce**
1. Go to App.Razor and upgrade to bootstrap 5.3.3:

2. Update the head:

`    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">`
  
 3. And body tags:
   
`  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>   `

Save and run. Now open up a modal with ShowCloseButton enabled. Close button in header slid to the left

**Comment by giarico** [comment]
It's a bootstrap bug:
https://github.com/twbs/bootstrap/issues/39798

It's going to be fixed in the next version.

**Comment by gvreddy04** [comment]
@XenoWizard Thank you for using BlazorBootstrap. Mean while you can set `HeaderCssClass="justify-content-between"`.
