### ISSUE TITLE
`Grid`'s property `EmptyDataTemplate` is not decorated as a `Parameter`.

### ISSUE THREAD

**Issue by kpavlov9** [vikramlearning/blazorbootstrap#717]
I am using version 2.2.0. When I use the component `Grid` the paramater from the documentation `EmptyDataTemplate` is not available, because it is not decorated with `Paramater` in the `Grid` implementation.

**Comment by gvreddy04** [comment]
@kpavlov9 Thank you for using BlazorBootstrap. We will check this.
