### ISSUE TITLE
GRID-  Server side filtering, paging and sorting

### ISSUE THREAD

**Issue by mrcorale** [vikramlearning/blazorbootstrap#754]
Hi, there is an issue with the lazy loading implementation in the grid. I have applied the necessary parameters, but the grid appears empty. However, the backend data is applied correctly. For any further clarification, I can email you the code to verify the logic!
![grid](https://github.com/vikramlearning/blazorbootstrap/assets/52911474/744deabb-275b-4b3b-a30e-b4d971558ba6)
![back-end](https://github.com/vikramlearning/blazorbootstrap/assets/52911474/d1c74906-f0c6-4851-9229-84ba761728fb)
![fron-end](https://github.com/vikramlearning/blazorbootstrap/assets/52911474/41c41d88-a7ed-4138-8f24-84601418c47a)

**Comment by gvreddy04** [comment]
@mrcorale Thank you for using BlazorBootstrap. Please share a sample GitHub repo with minimal steps to reproduce the issue.

**Comment by mrcorale** [comment]
https://github.com/mrcorale/BlazorBoostrap here the source cod to view

**Comment by gvreddy04** [comment]
@mrcorale I'm able to reproduce the issue. As you are using custom pagination, do not use the **request.PageNumber** and **request.PageSize**.

Before:
```csharp
var result = await dataWork.Employees.GetPaginatedAsync(request.PageNumber, request.PageSize, request.CancellationToken);
```

After fix:
```csharp
var result = await dataWork.Employees.GetPaginatedAsync(currentPageNumber, pgSize, request.CancellationToken);
```

Screenshot:
![image](https://github.com/vikramlearning/blazorbootstrap/assets/2337067/9e919089-25c2-4c2e-baf4-47b5f6d3d87f)

**Comment by mrcorale** [comment]
I am very grateful, thank you very much! I understand now!
