### ISSUE TITLE
Modal unreachable behind backdrop

### ISSUE THREAD

**Issue by IzaacJ** [vikramlearning/blazorbootstrap#756]
**Describe the bug**
When a component containing a modal is placed inside the top-bar, the modal gets rendered behind the backdrop, making it impossible to interact with.

**To Reproduce**

**Expected behavior**
A modal displaying above the backdrop.

**Screenshots**
<img width="596" alt="Screenshot 2024-06-16 at 07 26 22" src="https://github.com/vikramlearning/blazorbootstrap/assets/711323/4931f198-6831-4f57-8d49-19c47f1c5fe6">

**Versions (please complete the following information):**
 - .NET Version: .NET 8
 - BlazorBootstrap: 2.2.0
 - Blazor WebAssembly / Server: Server
 - Blazor Interactive Render Mode: Auto
 - Blazor Interactivity Location: Global

**Sample code**
```
<!-- MainLayout.razor -->
<main>
    <div class="bb-top-row px-4 d-flex justify-content-end">
        <ComponentWithModal />
    </div>
    <article class="content px-4">
        <div class="py-2">@Body</div>
    </article>
</main>
```

```
<!--- ComponentWithModal.razor -->
<Modal @ref="ModalExample" Title="Modal Example Behind Backdrop">
    <HeaderTemplate>
        Modal Header
    </HeaderTemplate>
    <BodyTemplate>
        Modal Body
    </BodyTemplate>
</Modal>
<Button @onclick="OnButtonClick"><Icon Name="IconName.BuildingGear" /></Button>

@code {
    private Modal ModalExample { get; set; }

    private async Task OnButtonClick() {
        await ModalExample.ShowAsync();
    }
}
```

**GitHub repo**
Setup an example here: https://github.com/izaacj/github-issues/tree/bb-modal

**Desktop (please complete the following information):**
 - OS: MacOS 14.5
 - Browser Safari
 - Version 17.5

**Comment by gvreddy04** [comment]
[Adding z-index: 1 to main area causes an active modal to sit behind its backdrop #39640](https://github.com/twbs/bootstrap/issues/39640)

**Comment by gvreddy04** [comment]
@IzaacJ Update the top row div css class as below:

```html
<div class="bb-top-row px-4 d-flex justify-content-end position-static">
    <ComponentWithModal />
</div>
```

**Screenshot:**

![image](https://github.com/vikramlearning/blazorbootstrap/assets/2337067/97ef2484-4df6-43a9-acdd-5034cfc26f48)

**Comment by IzaacJ** [comment]
That is only a partly working resolution, since the top-row stops being a top-row and scrolls with the content.
What I decided to do instead is change the bb-top-row z-index to 1055, keeping it sticky, but visually appearing above the backdrop, although not interactable, while the actual modal is interactable.

Just added the css below to the `app.css`

```css
.bb-top-row {
    z-index: 1055 !important;
}
```

Not a perfect workaround, but the top-row is kept sticky, which is more important in my case.
