### ISSUE TITLE
Grid HeaderCSS

### ISSUE THREAD

**Issue by vasuamics** [vikramlearning/blazorbootstrap#765]
**Describe the bug**
In Blazor Page added grid. Everything works except CSS class in header and filter

**To Reproduce**
Installed Blazor bootstrap . Add a page and a grid and add headercss class (copy from demo source)
**Expected behavior**
Header becomes blank (with white text)

**Screenshots**
![image](https://github.com/vikramlearning/blazorbootstrap/assets/173223651/f6a23b7a-6c39-4e35-86a4-4589674b6a1c)

**Versions (please complete the following information):**
 - .NET Version: [e.g. .NET 6, .NET 7, .NET 8]
 - BlazorBootstrap: [3.0.0-preview.1]
 - Blazor WebAssembly / Server: [e.g. WebAssembly, Server]

**Sample code**
<Grid @ref="gridViewUser" Style="" Height="30"
  TItem="AuthDbViewUser" class="table table-hover table-bordered table-striped mt-3"
  Data="Listusers"
  AllowRowClick="true"
  OnRowClick="OnRowClick"
  FixedHeader="true"
  ItemsPerPageText="Items Per Page"
  EmptyText="No records to display"
  AllowFiltering="true"
  PaginationItemsTextFormat="{0} - {1} of {2} items"
  PageSize="10" AllowPaging="true" AllowSorting="true"
  PageSizeSelectorItems="@(new int[] {2, 5,10,20 })"
  FiltersRowCssClass="bg-primary text-white bg-opacity-25 border-bottom-0"
  Unit="Unit.Em"
      Responsive="true">
<GridColumn TItem="AuthDbViewUser" HeaderText="Action" Filterable="false"  >
    <a href="#" style="margin-right:10px">Edit</a><a href="#">Delete</a> @*@onclick="OnShowModalClick"*@
</GridColumn>
</Grid>

**Comment by gvreddy04** [comment]
@vasuamics Thank you for trying BlazorBootstrap. Please refer to the issue below.

[Grid HeaderRowCSSClass and FiltersRowCSSClass still not working properly in 2.1 #621](https://github.com/vikramlearning/blazorbootstrap/issues/621)
