### ISSUE TITLE
Navigation Menu problem with Webassembly Net 8

### ISSUE THREAD

**Issue by Judhianto** [vikramlearning/blazorbootstrap#766]
Side menu not showing.

When I inspect in MainLayout.razor , and go to definition of SidebarDataProviderResult, I found this info

```
Resolve: 'System.Runtime, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
Found single assembly: 'System.Runtime, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
WARN: Version mismatch. Expected: '6.0.0.0', Got: '8.0.0.0'
Load from: 'C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\8.0.6\ref\net8.0\System.Runtime.dll'
```

please help...

**Comment by gvreddy04** [comment]
@Judhianto Thank you for using BlazorBootstrap. Please provide the below information

.NET Version: [e.g. .NET 6, .NET 7, .NET 8]
BlazorBootstrap: [e.g. 2.0.0, 2.1.0, 2.2.0]
Blazor WebAssembly / Server: [e.g. WebAssembly, Server]
Blazor Interactive Render Mode: [e.g. Auto, Server, WebAssembly, None]
Blazor Interactivity Location: [e.g. Global, Per page/component]
Sample code / GitHub repo with minimal steps to reproduce the issue:

**Comment by gvreddy04** [comment]
@Judhianto Feel free to create a new issue with a sample GitHub repository containing minimal steps to reproduce the issue. Closing for now.
