### ISSUE TITLE
Filter Grid Component

### ISSUE THREAD

**Issue by paulpitchford** [vikramlearning/blazorbootstrap#77]
Having used the grid component filtering seems to be a missing function to most grid components. There isn't a built in filtering method and simply filtering the bound entities doesn't refresh the grid in the UI. Being able to filter the component will be a really useful addition.

**Comment by gvreddy04** [comment]
@paulpitchford FYI

![image](https://user-images.githubusercontent.com/2337067/186772533-63a7acd2-c8b8-412a-8cb3-e80a222dd033.png)

![image](https://user-images.githubusercontent.com/2337067/186772667-e9747bcc-3dc0-4376-af6e-8146420ab585.png)

**Comment by gvreddy04** [comment]
@paulpitchford expect this component before Aug 31, 2022.
