### ISSUE TITLE
Grid: Add GridContainerClass Parameter

### ISSUE THREAD

**Issue by mrcorale** [vikramlearning/blazorbootstrap#776]
Hi, is it possible to add a CustomCss to add an additional class where class='table-responsive' is already preset, as shown in the image?
![custom-css](https://github.com/vikramlearning/blazorbootstrap/assets/52911474/5936a26c-a9bf-4766-9c9b-1c367d0e5cae)

**Comment by gvreddy04** [comment]
@mrcorale Thank you for using BlazorBootstrap. We currently don't have a provision to add the class to the GridContainer div tag. We will be adding this functionality in the next version.

**Comment by mrcorale** [comment]
Thank's !
