### ISSUE TITLE
Nested Off Canvases All Receive Events

### ISSUE THREAD

**Issue by buist-sharris** [vikramlearning/blazorbootstrap#78]
I am using the offcanvas in a project, and I am nesting them.  So, for example, I have an off canvas that displays job information which also has a nested off canvas that opens over top to show customer information for that job.  The issue I am running into, is the events (Showing, Hiding, etc) in the upper off canvas are also being picked up by the lower off canvas.  So for example, if I subscribe to the "OnHidden" event of the job info offcanvas to clear some values, when the customer offcanvas is closed, the job canvas's OnHidden event code is executed even though the job info offcanvas is still open.

This only happens when the "upper" offcanvas is nested inside the "lower" offcanvas.  If they are defined separately within the page, no issue.  However, for display purposes, it is sometimes beneficial to nest them to ensure they're properly "on top".

Is there a possible workaround (with IDs or something maybe) to resolve this?

**Comment by gvreddy04** [comment]
At this moment, we don't have a workaround for this. I will consider adding an Id shortly.

**Comment by buist-sharris** [comment]
I don't know that I would consider this an enhancement, and not a bug.  I'd consider it a bug when event handlers are receiving events from objects that they haven't subscribed to.

**Comment by gvreddy04** [comment]
@buist-sharris Can you share a sample code for a better understanding?

**Comment by buist-sharris** [comment]
Consider this code.  "Canvas One" has "Canvas Two" and "Canvas Three" inside its body template.  Once Canvas one is open, it will receive the show/hide events from both canvas two and three when they are fired.  Canvas two will not receive any of canvas three's events (or vice versa) because three is not nested inside two's body template.  If you were to nest three in two's body template, two would also get three's events.

Run the code, open canvas one, then two, then three, then close three, close two then close one.  Here's the output.

Open Canvas One...
Showing event received by Canvas one.
Shown event received by Canvas one.

Open Canvas Two...
Showing event received by Canvas two.
Showing event received by Canvas one. <--- canvas one shouldn't "see" this event, it's not its event
Shown event received by Canvas two.
Shown event received by Canvas one. <--- canvas one shouldn't "see" this event, it's not its event

Open Canvas Three...
Showing event received by Canvas three.
Showing event received by Canvas one.  <--- canvas one shouldn't "see" this event, it's not its event
Shown event received by Canvas three.
Shown event received by Canvas one. <--- canvas one shouldn't "see" this event, it's not its event

Close Canvas Three...
Hiding event received by Canvas three.
Hiding event received by Canvas one. <--- canvas one shouldn't "see" this event, it's not its event
Hidden event received by Canvas three.
Hidden event received by Canvas one. <--- canvas one shouldn't "see" this event, it's not its event
Canvas One Content is now showing the "hidden" message <--- This is the really bad part of this bug.

Close Canvas Two...
Hiding event received by Canvas two.
Hiding event received by Canvas one. <--- canvas one shouldn't "see" this event, it's not its event
Hidden event received by Canvas two. 
Hidden event received by Canvas one. <--- canvas one shouldn't "see" this event, it's not its event

Close Canvas One...
Hiding event received by Canvas one.
Hidden event received by Canvas one.

It would seem that the canvas needs some way of identifying "this is my event to respond to, not another canvas's event".

```html
<button @onclick="()=> CanvasOne.ShowAsync()">Open Canvas One</button>

<BlazorBootstrap.Offcanvas @ref="CanvasOne"
                           IsScrollable="true"
                           UseBackdrop="true"
                           Size="BlazorBootstrap.OffcanvasSize.Large"
                           Placement="BlazorBootstrap.Placement.End"
                           OnHiding="@(()=> System.Diagnostics.Debug.WriteLine("Hiding event received by Canvas one."))"
                           OnShowing="@(()=> System.Diagnostics.Debug.WriteLine("Showing event received by Canvas one."))"
                           OnHidden="CanvasOneHidden"
                           OnShown="@(()=> System.Diagnostics.Debug.WriteLine("Shown event received by Canvas one."))">
    <HeaderTemplate>
        <h5 class="offcanvas-title">Canvas One Header</h5>
    </HeaderTemplate>
    <BodyTemplate>
        <button @onclick="()=> CanvasTwo.ShowAsync()">Open Canvas Two</button>
        
        @if (IsHidingCanvasOneContent)
        {
            <p>Canvas One Content was Hidden...From the events called when Canvas two or three closed, not its own events.</p>
        }
        else
        {
            <p>Hello World, I am canvas one&apos;s content.</p>
        }
        
        <BlazorBootstrap.Offcanvas @ref="CanvasTwo"
                                   IsScrollable="true"
                                   UseBackdrop="true"
                                   Size="BlazorBootstrap.OffcanvasSize.Large"
                                   Placement="BlazorBootstrap.Placement.End"
                                   OnHiding="@(()=> System.Diagnostics.Debug.WriteLine("Hiding event received by Canvas two."))"
                                   OnShowing="@(()=> System.Diagnostics.Debug.WriteLine("Showing event received by Canvas two."))"
                                   OnHidden="@(()=> System.Diagnostics.Debug.WriteLine("Hidden event received by Canvas two."))"
                                   OnShown="@(()=> System.Diagnostics.Debug.WriteLine("Shown event received by Canvas two."))">
            <HeaderTemplate>
                <h5 class="offcanvas-title">Canvas Two Header</h5>
            </HeaderTemplate>
            <BodyTemplate>
                <p>Canvas Two Body</p>
                <button @onclick="()=> CanvasThree.ShowAsync()">Open Canvas Three</button>
            </BodyTemplate>
        </BlazorBootstrap.Offcanvas>

        <BlazorBootstrap.Offcanvas @ref="CanvasThree"
                                   IsScrollable="true"
                                   UseBackdrop="true"
                                   Size="BlazorBootstrap.OffcanvasSize.Large"
                                   Placement="BlazorBootstrap.Placement.End"
                                   OnHiding="@(()=> System.Diagnostics.Debug.WriteLine("Hiding event received by Canvas three."))"
                                   OnShowing="@(()=> System.Diagnostics.Debug.WriteLine("Showing event received by Canvas three."))"
                                   OnHidden="@(()=> System.Diagnostics.Debug.WriteLine("Hidden event received by Canvas three."))"
                                   OnShown="@(()=> System.Diagnostics.Debug.WriteLine("Shown event received by Canvas three."))">
            <HeaderTemplate>
                <h5 class="offcanvas-title">Canvas Three Header</h5>
            </HeaderTemplate>
            <BodyTemplate>
                <p>Canvas Three Body</p>
            </BodyTemplate>
        </BlazorBootstrap.Offcanvas>
    </BodyTemplate>
</BlazorBootstrap.Offcanvas>

@code {
    private BlazorBootstrap.Offcanvas CanvasOne { get; set; }
    private BlazorBootstrap.Offcanvas CanvasTwo { get; set; }
    private BlazorBootstrap.Offcanvas CanvasThree { get; set; }
    private bool IsHidingCanvasOneContent { get; set; }

    private void CanvasOneHidden()
    {
        System.Diagnostics.Debug.WriteLine("Hidden event received by Canvas one.");
        IsHidingCanvasOneContent = true;
    }
}
```

**Comment by gvreddy04** [comment]
![image](https://user-images.githubusercontent.com/2337067/183741787-4f58d059-d705-4c60-8ffa-db9b8aa8d1c2.png)

Link: https://getbootstrap.com/docs/5.1/components/offcanvas/#how-it-works

**Comment by gvreddy04** [comment]
@buist-sharris Still, I'm investigating the other options.

**Comment by gvreddy04** [comment]
@buist-sharris You can now use one off-canvas with **accordion** or **div** (with toggle option) to show the customer information.

**Comment by buist-sharris** [comment]
OK, thanks.  I'll continue to do hacks in my project to make it work.  Unfortunately, the UI of my project really requires multiple canvases being open as they represent other "areas" of my project that are dispersed throughout and are very context dependent.   div or accordions would make it impossible to create re-usable components.

**Comment by gvreddy04** [comment]
@buist-sharris Thanks for using `Blazor.Bootstrap` components.

**Comment by gvreddy04** [comment]
@buist-sharris Nested offcanvas is not supported. We do not have plans to implement this. If we get more requests, then we will see again.
