### ISSUE TITLE
Submember indentation is not possible in languages ​​other than English in the Blazor Sidebar 2 component.

### ISSUE THREAD

**Issue by NezihOzkanHd** [vikramlearning/blazorbootstrap#787]
**Describe the bug**
Submember indentation is not possible in languages ​​other than English in the Blazor Sidebar 2 component.

**To Reproduce**
![image](https://github.com/vikramlearning/blazorbootstrap/assets/89746797/95ed1e2a-7bb7-4361-8b88-498dfe81ca4d)

**Expected behavior**
![image](https://github.com/vikramlearning/blazorbootstrap/assets/89746797/c8c44972-465b-4bc0-abf9-bcd010b2a391)

![image](https://github.com/vikramlearning/blazorbootstrap/assets/89746797/8626e390-ed7c-4939-8f29-5fecba1fa3bb)

**Versions (please complete the following information):**
 - .NET Version: NET 8

**Sample code**
 private string GetNavLinkStyle()
 {
     // Implementation:
     // Level 0 = 1rem    = 0 + 1 + (0 * 0.5)
     // Level 1 = 2.5rem  = 1 + 1 + (1 * 0.5)
     // Level 2 = 4rem    = 2 + 1 + (2 * 0.5)
     // ...
     // Level n = .....   = n + 1 + (n * 0.5)

     var level = Level + 1 + Level * 0.5;

     if (HasChilds && !NavItemGroupExpanded)
         level += 0.25;
     else if (!HasChilds && Level == 0)
         level += 0.25;

     // NezihOzkan level value must be (en-US) culture specific, otherwise the dot sign becomes a comma in other languages.
     //return $"padding-left:{level}rem;";
     return $"padding-left:{level.ToString(CultureInfo.CreateSpecificCulture("en-US"))}rem;";
 }

**Comment by gvreddy04** [comment]
@NezihOzkanHd Thank you for using BlazorBootstrap. You can try using `.ToString(CultureInfo.InvariantCulture)`. We will fix this in the next version.
