### ISSUE TITLE
Tabs - get active tab

### ISSUE THREAD

**Issue by lartusi** [vikramlearning/blazorbootstrap#813]
Maybe I missed it in the documentation.
But, how can I get the active tab object or the active tab's name?

Thank you!

**Comment by gvreddy04** [comment]
@lartusi  Thank you for using BlazorBootstrap. There is no public method available to get the active tab object or name. However, you can capture the active tab object with the `OnShown` event.

Docs: https://docs.blazorbootstrap.com/components/tabs#tabs-callback-events
Demo: https://demos.blazorbootstrap.com/tabs#events-example

**Comment by lartusi** [comment]
Thank you for the quick reply.
In my opinion is better to expose the entire tab object in the TabsEventArgs or at least the Name property.

**Comment by gvreddy04** [comment]
@lartusi Will add in the upcoming release.
