### ISSUE TITLE
Sidebar Inside a Component

### ISSUE THREAD

**Issue by wowraam** [vikramlearning/blazorbootstrap#822]
Dear Vikram,
Firstly, Thank you for the wonderful work. I just started using blazorbootstrap based on Sidebar2 example.

As soon as I add it to my code, noticed that it is always showing mobile menu. I tried passing isMobile false using additionalattributes but still its same. can you help?

here is the code.
    <Sidebar2 Href="/"
              IconName="IconName.Folder"
              Title="Study Name"
              BadgeText="status"
              AdditionalAttributes="@(new Dictionary<string, object> {
                { "collapseNavMenu", "false"},
                { "collapseSidebar", "false"},
                { "isMobile", "false"},
                })"
              DataProvider="Sidebar2DataProvider" />

Here is the screenshot.

![image](https://github.com/user-attachments/assets/fd3d339b-154c-4bba-b84a-ca94c66d9be1)

**Comment by gvreddy04** [comment]
@wowraam Thank you for using BlazorBootstrap. Please share a sample GitHub repo with minimal steps to reproduce the issue.
