### ISSUE TITLE
Map component

### ISSUE THREAD

**Issue by kperez0697** [vikramlearning/blazorbootstrap#826]
something like this 
![image](https://github.com/user-attachments/assets/3500d545-3fb3-48e4-8449-81677c4f6198)

**Comment by kperez0697** [comment]
this example i saw here https://blazor.radzen.com/googlemap?theme=material3

**Comment by gvreddy04** [comment]
Screenshot:

![image](https://github.com/user-attachments/assets/4968a3fd-cd2a-4178-8dc4-762f574135bf)
