### ISSUE TITLE
Refresh items in nested grid...

### ISSUE THREAD

**Issue by prizmasoftware** [vikramlearning/blazorbootstrap#842]
Maybe I'm wrong in something, but I have the impression today that something is not working regarding the grid and subgrid:
When I try to delete a row from the subgrid list, by deleting it from the database, you need to refresh that subgrid to display it without the deleted row. You will logically use grid.RefreshDataAsync(), and/or subgrid.RefreshDataAsync(), but this method does not recognize which subgrid is changed and will not refresh it, only the last one.
Specifically, if you have 3 items in grid and three subgrids with several items each, if you delete the row in subgrid of the second item, it will not be refreshed, the subgrid of the third item will be refreshed, so the refresh will actually work only when you delete rows from the last subgrid.
Sample of nested grid:
Grid 1
...... Item 1
...... Item 2
Grid 2
...... Item 1
...... Item 2
...... Item 3
Grid 3
...... Item 1
...... Item 2

**Comment by gvreddy04** [comment]
@prizmasoftware Thanks you for using **BlazorBootstrap**. We will handle this issue part of https://github.com/vikramlearning/blazorbootstrap/issues/827.
