### ISSUE TITLE
Dropdown: Documentation not up to date

### ISSUE THREAD

**Issue by Crashdummyy** [vikramlearning/blazorbootstrap#865]
**Describe the bug**
Your current [Documentation](https://docs.blazorbootstrap.com/components/dropdown#color) is not correct anymore.
Tne dropdown doesnt work after ParameterSet

**To Reproduce**
```html
    <Dropdown>
        <DropdownToggleButton Color="ButtonColor.Primary">Primary</DropdownToggleButton>
        <DropdownMenu>
            <DropdownItem To="#" Type="ButtonType.Link">Action</DropdownItem>
            <DropdownItem To="#" Type="ButtonType.Link">Another action</DropdownItem>
            <DropdownItem To="#" Type="ButtonType.Link">Something else here</DropdownItem>
        </DropdownMenu>
    </Dropdown>
```

**Expected behavior**
It appears like Color migrated to a CascadingParameter

```html
    <Dropdown Color="DropdownColor.Primary">
        <DropdownToggleButton>Primary</DropdownToggleButton>
        <DropdownMenu>
            <DropdownItem To="#" Type="ButtonType.Link">Action</DropdownItem>
            <DropdownItem To="#" Type="ButtonType.Link">Another action</DropdownItem>
            <DropdownItem To="#" Type="ButtonType.Link">Something else here</DropdownItem>
        </DropdownMenu>
    </Dropdown>
```

**Screenshots**
![image](https://github.com/user-attachments/assets/b49e0bf3-c1f8-4260-9049-8eeab97beee8)

**Versions (please complete the following information):**
 - .NET Version:.NET 8
 - BlazorBootstrap: 3.0.0
 - Blazor WebAssembly / Server:  Webassembly hosted
 - Blazor Interactive Render Mode: Webassembly
 - Blazor Interactivity Location: Global

**Desktop (please complete the following information):**
 - OS: Arch Linux on 6.11
 - Browser Librewolf
 - Version 129.0

**Comment by gvreddy04** [comment]
@Crashdummyy Thank you for reporting this. We will fix this.
