### ISSUE TITLE
Support StringComparison options for filtering

### ISSUE THREAD

**Issue by sanderweltje** [vikramlearning/blazorbootstrap#91]
When filtering on a type string the filter is case sensitive. Is it possible to support System.StringComparison so I can use InvariantCultureIgnoreCase. For example:
- Extend the function GridDataProviderRequest.ApplyTo() with an extra parameter System.StringComparison 
- Add a FilterSelector option similar as done for sorting SortKeySelector. Custom filter logic can be added this way

**Comment by gvreddy04** [comment]
@gvreddy04 Apply the same feature for both AutoComplete and Grid.

**Comment by sanderweltje** [comment]
Works like a charm, thanks!
