### ISSUE TITLE
From version 3.0.0 to 3.1.0 in Blazor web assembly

### ISSUE THREAD

**Issue by Trinita75** [vikramlearning/blazorbootstrap#912]
In a Blazor .net core 8 Web Assembly project, upgrading from Nuget Package, from 3.0.0 to 3.1.0 you get this error

Method not found: Microsoft.Extensions.DependencyInjection.IServiceCollection Microsoft.Extensions.DependencyInjection.Config.AddBlazorBootstrap(Microsoft.Extensions.DependencyInjection.IServiceCollection,Microsoft.Extensions.Configuration.IConfiguration)

**Comment by gvreddy04** [comment]
@Trinita75 Thank you for using **BlazorBootstrap**. I don't see any issues while upgrading from 3.0.0 to 3.1.0. Please check the starter template at https://github.com/vikramlearning/blazorbootstrap-starter-templates/tree/master/src/BlazorBootstrap.Templates.Starter/NET8.BlazorWebAssemblyStandaloneApp.

If you still see the issue, please create a GitHub repository with minimal steps to reproduce the issue.

NOTE: Do not include any sensitive information.

**Comment by gvreddy04** [comment]
@Trinita75 Feel free to create a new issue if you need any help. Closing for now as there are no updates.
