### ISSUE TITLE
The Blazor PDF Viewer is not supporting certain fonts

### ISSUE THREAD

**Issue by Mostafa-Moradi** [vikramlearning/blazorbootstrap#919]
Hi,
Thank you for your very good package.
I have a PDF file in Persian format that is unreadable when displayed with PDF Viewer.
The letters are cut out.
See the attached file
![Screenshot 2024-10-29 105954](https://github.com/user-attachments/assets/c271e07d-2407-4c29-bd00-c680a34c0210)

**Comment by muthu04439** [comment]
@Mostafa-Moradi Thank you for using BlazorBootstrap. Can you attach a sample PDF file to test the scenario.

**Comment by Mostafa-Moradi** [comment]
Hi, @muthu04439 
File link:
https://docs.crouse.ir/cdn/file/downloadfile/news/otscmi2b1qf.pdf

**Comment by gvreddy04** [comment]
> Hi, @muthu04439 File link: https://docs.crouse.ir/cdn/file/downloadfile/news/otscmi2b1qf.pdf

@Mostafa-Moradi  We are unable to load the PDF from the specified URL. Please attach a file here.

**Comment by Mostafa-Moradi** [comment]
[Uploading otscmi2b1qf.pdf…]()

**Comment by Mostafa-Moradi** [comment]
[otscmi2b1qf.pdf](https://github.com/user-attachments/files/17592753/otscmi2b1qf.pdf)

**Comment by gvreddy04** [comment]
> [otscmi2b1qf.pdf](https://github.com/user-attachments/files/17592753/otscmi2b1qf.pdf)

I'll check this.

**Comment by gvreddy04** [comment]
@Mostafa-Moradi Tested with the attached document, I don't see any issue. Please see the following screenshot.

![image](https://github.com/user-attachments/assets/2a2afd0d-9065-456c-9866-db10f81b7780)

Let me know if you have any questions.

**Comment by Mostafa-Moradi** [comment]
@gvreddy04  I proceeded with my project and installed version 3.1.1 according to the instructions on the page: https://docs.blazorbootstrap.com/getting-started/blazor-webapp-server-global-net-8. 
But my problem is not solved.

**Comment by gvreddy04** [comment]
@Mostafa-Moradi No worries. Please create a GitHub repository with minimal steps to reproduce the issue. I can take a look.

**Comment by Mostafa-Moradi** [comment]
@gvreddy04 Thank you, the problem has been solved since you posted it
