### ISSUE TITLE
Charts keeps changing size (Edge only)

### ISSUE THREAD

**Issue by DYZ-H** [vikramlearning/blazorbootstrap#958]
**Describe the bug**
I find charts have a bug
When the browser is zoomed in 110 degrees, it keeps changing size，cannot be determined。As shown in the following pictures, the official website example has the same problem。

**Screenshots**
![image](https://github.com/user-attachments/assets/07285f36-2c61-4df1-b34b-aa98e51297dc)
![image](https://github.com/user-attachments/assets/719ef42c-8db7-4b58-b7e1-74ddaa9f90b5)

**Versions (please complete the following information):**
 - .NET Version: [.NET 8]
 - BlazorBootstrap: [3.2.0]
 - Blazor Server
 - Blazor Interactive Render Mode: [ Server,]

**Desktop (please complete the following information):**
 - OS: [windows]
 - Browser [edge]

**Comment by AldebaranPrimo** [comment]
Same problem! 
Edge v132, zoom 155%

![Blazor Charts bug](https://github.com/user-attachments/assets/4182775f-a44e-4cf1-85a5-3de2de2b4cda)

**Comment by gvreddy04** [comment]
@DYZ-H @AldebaranPrimo Thank you for reporting this.

**Comment by DYZ-H** [comment]
@gvreddy04  Thank you very much,issue fixed.
