### ISSUE TITLE
How to add Modal Parameters using ShowAsync<T>(string title, Dictionary<string, object> parameters = null)

### ISSUE THREAD

**Issue by YouriOkken** [vikramlearning/blazorbootstrap#970]
Hi, I am new to Blazor Bootstrap. I have a very simple question.

How do I pass Modal Parameters such as HeaderCssClass, IsVerticallyCentered, etc. using the ShowAsync<T>(string title, Dictionary<string, object> parameters = null)?

I cant find any info about this on the docs

Kind regards

**Comment by gvreddy04** [comment]
@YouriOkken Thank you for trying BlazorBootstrap. We will add more examples for your use case.

## Example:
```cshtml
<Modal @ref="modal" title="Modal title" IsVerticallyCentered="true" HeaderCssClass="custom-modal-header">
    <BodyTemplate>
        . . . 
    </BodyTemplate>
    <FooterTemplate>
        . . . 
    </FooterTemplate>
</Modal>
```

Link: https://demos.blazorbootstrap.com/modals#vertically-centered

**Comment by gvreddy04** [comment]
@YouriOkken Please check the discussion #971.
