### ISSUE TITLE
Grid, position of PageSizeSelector, PaginationItemsText and ItemsPerPageText row.

### ISSUE THREAD

**Issue by prizmasoftware** [vikramlearning/blazorbootstrap#980]
I'm not sure if I'm right, but it seems to me that the position of the row below the grid where the PageSizeSelector, PaginationItemsText and ItemsPerPageText are placed is fixed, no matter how many rows per page are set. In fact, the height of the "page" is always the same, and the elements inside the page scroll if they exceed the height of the "page", which is fixed (about 5 rows). 
This leads to the fact that even though there is enough space on the screen to display, for example, 10 rows without the need for scrolling, about 5 are displayed, with the rest scrolling, and with half the screen empty.
In the second case, when I have 1 or 2 rows in the grid, there is a disproportionately large space between the last row and the row with the PageSizeSelector, PaginationItemsText and ItemsPerPageText.
If there is a way to dynamically or fixedly set the spacing between the last row in the grid and the row with the PageSizeSelector, PaginationItemsText and ItemsPerPageText, I would like someone to tell me how.

**Comment by gvreddy04** [comment]
@prizmasoftware 

Can you check the demo once: https://demos.blazorbootstrap.com/grid/overview

## Screenshot:

![image](https://github.com/user-attachments/assets/dff89d8f-04a2-4b6b-b987-41f6ef69f6a2)

**Comment by prizmasoftware** [comment]
Thanks for the answer, although it would have been easier if you had directed me to the FixedHeader property, which determines whether the Header will scroll or not. The grid overview demo does not mention...
For anyone who may have a dilemma:
If FixedHeader=True, you need to specify a fixed grid height, which is actually the empty space that was the problem for me.
Finally, if FixedHeader=false, the row with the PageSelector is immediately after the last row of the grid, otherwise there is a gap in between, defined by the grid height.
Thanks again.
