### ISSUE TITLE
Preserve grid filter settings

### ISSUE THREAD

**Issue by sanderweltje** [vikramlearning/blazorbootstrap#99]
I like to preserve the state of my grid filter settings so when navigating away and back again I can reapply the filter. Currently it's not possible to get the filter value from the column as it's set in a private field and the public parameter is not updated. What is the best way to preserve the state of the grid filter?

**Comment by gvreddy04** [comment]
@sanderweltje At this moment, we support default filters only. But you can add multiple filters. I will add this as an enhancement.

![image](https://user-images.githubusercontent.com/2337067/190957589-4b035034-7e1e-4c8c-9a30-bd879d84c39f.png)

Link: https://demos.getblazorbootstrap.com/grid#set-default-filter

**Comment by sanderweltje** [comment]
I only need one default filter. What I want to do is store the filter settings the user changed to SessionStorage https://learn.microsoft.com/en-us/aspnet/core/blazor/state-management?view=aspnetcore-6.0&pivots=server#browser-storage-server. So when the page is reloaded in the same session I can restore the filter settings. The problem is that the GridColumn FilterValue and FilterOperator are never changed because the value is stored in a private field. I would like to get and set the FilterValue and FilterIOperator from code.

**Comment by gvreddy04** [comment]
@sanderweltje FYI

**Comment by gvreddy04** [comment]
@sanderweltje done
